-- V014: reset disposable demo data and populate a broad realistic test dataset.
PRAGMA foreign_keys=OFF;
ALTER TABLE transactions ADD COLUMN transaction_ref TEXT;
ALTER TABLE transactions ADD COLUMN updated_at TEXT;
DELETE FROM token_assignments;
DELETE FROM token_events;
DELETE FROM certificates;
DELETE FROM deaths;
DELETE FROM marriages;
DELETE FROM welfare_requests;
DELETE FROM transactions;
DELETE FROM donations;
DELETE FROM subscriptions;
DELETE FROM members;
DELETE FROM families;
DELETE FROM audit_log;
DELETE FROM notifications;

INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (1,'FAM-001','Darussalam','1','1','Nadakkavu','Darussalam, Nadakkavu, Kozhikode','673011','9847001001','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (2,'FAM-002','Noor Manzil','2','2','Moozhikkal','Noor Manzil, Moozhikkal, Kozhikode','673010','9847001002','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (3,'FAM-003','Rahmath','3','3','Vellimadukunnu','Rahmath, Vellimadukunnu, Kozhikode','673012','9847001003','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (4,'FAM-004','Al Huda','4','4','Kottooli','Al Huda, Kottooli, Kozhikode','673016','9847001004','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (5,'FAM-005','Mubarak','5','5','Malaparamba','Mubarak, Malaparamba, Kozhikode','673009','9847001005','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (6,'FAM-006','Safiya House','6','6','Chevayur','Safiya House, Chevayur, Kozhikode','673017','9847001006','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (7,'FAM-007','Madinah','7','7','Pottammal','Madinah, Pottammal, Kozhikode','673016','9847001007','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (8,'FAM-008','Hidaya','8','8','Palazhi','Hidaya, Palazhi, Kozhikode','673014','9847001008','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (9,'FAM-009','Fathima Manzil','9','1','Kunduparamba','Fathima Manzil, Kunduparamba, Kozhikode','673007','9847001009','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (10,'FAM-010','Safa Villa','10','2','Eranhipalam','Safa Villa, Eranhipalam, Kozhikode','673006','9847001010','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (11,'FAM-011','Rahma House','11','3','Feroke','Rahma House, Feroke, Kozhikode','673631','9847001011','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (12,'FAM-012','Amina Manzil','12','4','Ramanattukara','Amina Manzil, Ramanattukara, Kozhikode','673633','9847001012','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (13,'FAM-013','Naseema','13','5','Pantheerankavu','Naseema, Pantheerankavu, Kozhikode','673019','9847001013','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (14,'FAM-014','Shifa','14','6','Kallai','Shifa, Kallai, Kozhikode','673003','9847001014','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (15,'FAM-015','Mariya House','15','7','West Hill','Mariya House, West Hill, Kozhikode','673005','9847001015','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (16,'FAM-016','Zamzam','16','8','Medical College','Zamzam, Medical College, Kozhikode','673008','9847001016','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (17,'FAM-017','Green View','17','1','Puthiyangadi','Green View, Puthiyangadi, Kozhikode','673021','9847001017','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (18,'FAM-018','Noor Palace','18','2','Govindapuram','Noor Palace, Govindapuram, Kozhikode','673016','9847001018','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (19,'FAM-019','Al Madina','19','3','Mankavu','Al Madina, Mankavu, Kozhikode','673007','9847001019','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (20,'FAM-020','Rahma Villa','20','4','Parayancheri','Rahma Villa, Parayancheri, Kozhikode','673004','9847001020','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (21,'FAM-021','Hidaya House','21','5','Karaparamba','Hidaya House, Karaparamba, Kozhikode','673010','9847001021','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (22,'FAM-022','Baitul Noor','22','6','Thondayad','Baitul Noor, Thondayad, Kozhikode','673017','9847001022','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (23,'FAM-023','Darul Aman','23','7','Arayidathupalam','Darul Aman, Arayidathupalam, Kozhikode','673004','9847001023','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (24,'FAM-024','Anwar Manzil','24','8','Mananchira','Anwar Manzil, Mananchira, Kozhikode','673001','9847001024','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (25,'FAM-025','Safa Manzil','25','1','Kozhikode Beach','Safa Manzil, Kozhikode Beach, Kozhikode','673032','9847001025','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (26,'FAM-026','Afsar Villa','26','2','Nadakkavu East','Afsar Villa, Nadakkavu East, Kozhikode','673011','9847001026','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (27,'FAM-027','Barakah','27','3','Pokkunny','Barakah, Pokkunny, Kozhikode','673007','9847001027','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (28,'FAM-028','Misk','28','4','Kommeri','Misk, Kommeri, Kozhikode','673007','9847001028','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (29,'FAM-029','Riyaz House','29','5','Kakkodi','Riyaz House, Kakkodi, Kozhikode','673611','9847001029','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (30,'FAM-030','Tasneem','30','6','Kunnamangalam','Tasneem, Kunnamangalam, Kozhikode','673571','9847001030','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (31,'FAM-031','Ilham','31','7','Elathur','Ilham, Elathur, Kozhikode','673303','9847001031','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (32,'FAM-032','Rafeeq Manzil','32','8','Athanikkal','Rafeeq Manzil, Athanikkal, Kozhikode','673637','9847001032','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (33,'FAM-033','Thaj Manzil','33','1','Beypore','Thaj Manzil, Beypore, Kozhikode','673015','9847001033','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (34,'FAM-034','Afnan House','34','2','Chalappuram','Afnan House, Chalappuram, Kozhikode','673002','9847001034','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (35,'FAM-035','Jannath','35','3','Puthiyara','Jannath, Puthiyara, Kozhikode','673004','9847001035','Active','Demo dataset');
INSERT INTO families (id,family_number,house_name,house_number,ward,area,address,pincode,phone,status,notes) VALUES (36,'FAM-036','Naseem Villa','36','4','Ramanattukara East','Naseem Villa, Ramanattukara East, Kozhikode','673633','9847001036','Active','Demo dataset');

INSERT INTO members (id,family_id,member_code,name,gender,date_of_birth,age,blood_group,occupation,education,marital_status,mobile,email,nationality,relationship,is_head,status) VALUES (1,1,'MEM-001','Abdul Rahman','Male','1973-02-12',53,'O+','Business Owner','B.Com','Married','9847200001','demo001@example.com','Indian','Head',1,'Active');
INSERT INTO members (id,family_id,member_code,name,gender,date_of_birth,age,blood_group,occupation,education,marital_status,mobile,email,nationality,relationship,is_head,status) VALUES (2,1,'MEM-002','Fathima','Female','1979-04-18',47,'A+','Teacher','B.Ed','Married','9847200002','demo002@example.com','Indian','Spouse',0,'Active');
INSERT INTO members (id,family_id,member_code,name,gender,date_of_birth,age,blood_group,occupation,education,marital_status,mobile,email,nationality,relationship,is_head,status) VALUES (3,1,'MEM-003','Ayaan Rahman','Male','2008-06-10',18,'B+','Student','Plus Two','Single','9847200003','demo003@example.com','Indian','Son',0,'Active');
INSERT INTO members (id,family_id,member_code,name,gender,date_of_birth,age,blood_group,occupation,education,marital_status,mobile,email,nationality,relationship,is_head,status) VALUES (4,2,'MEM-004','Muhammed Shafi','Male','1972-03-10',54,'O+','Civil Engineer','B.Tech','Married','9847200004','demo004@example.com','Indian','Head',1,'Active');
INSERT INTO members (id,family_id,member_code,name,gender,date_of_birth,age,blood_group,occupation,education,marital_status,mobile,email,nationality,relationship,is_head,status) VALUES (5,2,'MEM-005','Rukiya','Female','1978-05-11',48,'A+','Homemaker','Higher Secondary','Married','9847200005','demo005@example.com','Indian','Spouse',0,'Active');
INSERT INTO members (id,family_id,member_code,name,gender,date_of_birth,age,blood_group,occupation,education,marital_status,mobile,email,nationality,relationship,is_head,status) VALUES (6,2,'MEM-006','Ibrahim Shafi','Male','2007-08-19',19,'B+','Software Developer','BCA','Single','9847200006','demo006@example.com','Indian','Son',0,'Active');
INSERT INTO members (id,family_id,member_code,name,gender,date_of_birth,age,blood_group,occupation,education,marital_status,mobile,email,nationality,relationship,is_head,status) VALUES (7,3,'MEM-007','Niyas','Male','1973-01-15',53,'O+','Accountant','M.Com','Married','9847200007','demo007@example.com','Indian','Head',1,'Active');
INSERT INTO members (id,family_id,member_code,name,gender,date_of_birth,age,blood_group,occupation,education,marital_status,mobile,email,nationality,relationship,is_head,status) VALUES (8,3,'MEM-008','Shahana','Female','1980-02-22',46,'A+','Teacher','M.A.','Married','9847200008','demo008@example.com','Indian','Spouse',0,'Active');
