const DICT: Record<string, string> = {
  mahallu:"മഹല്ല്", mahal:"മഹൽ", muhammed:"മുഹമ്മദ്", mohammed:"മുഹമ്മദ്", muhammad:"മുഹമ്മദ്", abdul:"അബ്ദുൽ", rahman:"റഹ്മാൻ", rahim:"റഹീം", hidayathul:"ഹിദായത്തുൽ", hidayath:"ഹിദായത്ത്", islam:"ഇസ്‌ലാം", kondotty:"കൊണ്ടോട്ടി", malappuram:"മലപ്പുറം", kozhikode:"കോഴിക്കോട്", calicut:"കോഴിക്കോട്", kerala:"കേരള", qazi:"ഖാസി", qaswa:"ഖസ്വ", masjid:"മസ്ജിദ്", madrasa:"മദ്റസ", committee:"കമ്മിറ്റി", family:"കുടുംബം", house:"വീട്", ward:"വാർഡ്", venue:"വേദി", eid:"ഈദ്", ramadan:"റമദാൻ", nikah:"നികാഹ്", marriage:"വിവാഹം", death:"മരണം", welfare:"ക്ഷേമം", donation:"സംഭാവന", token:"ടോക്കൺ", card:"കാർഡ്", number:"നമ്പർ"
};
const VOWELS:Array<[string,string]>=[["aa","ആ"],["ee","ഈ"],["ii","ഈ"],["oo","ഊ"],["uu","ഊ"],["ai","ഐ"],["au","ഔ"],["ae","ഏ"],["a","അ"],["i","ഇ"],["u","ഉ"],["e","എ"],["o","ഒ"]];
const SIGNS:Record<string,string>={aa:"ാ",ee:"ീ",ii:"ീ",oo:"ൂ",uu:"ൂ",ai:"ൈ",au:"ൗ",ae:"േ",i:"ി",u:"ു",e:"െ",o:"ൊ"};
const CONS:Array<[string,string]>=[["ksh","ക്ഷ"],["ng","ങ"],["nj","ഞ"],["chh","ഛ"],["ch","ച"],["jh","ഝ"],["gh","ഘ"],["kh","ഖ"],["th","ത"],["dh","ധ"],["ph","ഫ"],["bh","ഭ"],["sh","ശ"],["zh","ഴ"],["ll","ള"],["rr","റ"],["tt","റ്റ"],["dd","ഡ"],["nn","ന"],["ny","ഞ"],["k","ക"],["g","ഗ"],["j","ജ"],["c","ച"],["t","ത"],["d","ദ"],["n","ന"],["p","പ"],["b","ബ"],["m","മ"],["y","യ"],["r","ര"],["l","ല"],["v","വ"],["w","വ"],["s","സ"],["h","ഹ"],["f","ഫ"],["q","ഖ"],["x","ക്സ"],["z","സ"]];
function match<T>(list:Array<[string,T]>,s:string,i:number){for(const [k,v] of list)if(s.startsWith(k,i))return [k,v] as [string,T];return null;}
function transliterateWord(raw:string){const lower=raw.toLowerCase();if(DICT[lower])return DICT[lower];if(/[^a-z]/i.test(raw)||!/[a-z]/i.test(raw))return raw;let out="";let i=0;while(i<lower.length){const v=match(VOWELS,lower,i),c=match(CONS,lower,i);if(v&&(!c||v[0].length>=c[0].length)){out+=v[0]==="a"?"അ":v[1];i+=v[0].length;continue;}if(c){const [ck,cv]=c;const next=match(VOWELS,lower,i+ck.length);out+=cv;if(next){if(next[0]!=="a")out+=SIGNS[next[0]];i+=ck.length+next[0].length;}else{if(match(CONS,lower,i+ck.length))out+="്";i+=ck.length;}continue;}out+=raw[i++];}return out;}
export function transliterateMalayalam(value:string){return value.split(/(\s+|[-/,.;:()]+)/).map(part=>{if(!part||/^\s+$/.test(part)||/^[-/,.;:()]+$/.test(part)||/[\u0D00-\u0D7F]/.test(part))return part;return transliterateWord(part);}).join("");}
