import { contextBridge, ipcRenderer } from "electron";

/**
 * Electron wraps EVERY rejected ipcMain.handle as
 *   "Error invoking remote method '<channel>': Error: <actual message>"
 * That technical, English-only wrapper used to leak verbatim into user-facing
 * toasts all over the app (password round fixed the auth surfaces; this fixes
 * the whole class in one place — WhatsApp "not connected", "No internet
 * connection", PDF failures, SQLite guards, everything). Strip it once here
 * so every renderer catch site only ever sees the actionable sentence.
 */
async function invoke(channel: string, ...args: unknown[]): Promise<any> {
  try {
    return await ipcRenderer.invoke(channel, ...args);
  } catch (e: unknown) {
    const raw = e instanceof Error ? e.message : String(e);
    const m = raw.match(/^Error invoking remote method '[^']+':\s*(?:Error:\s*)?([\s\S]*)$/);
    throw new Error(m ? m[1] : raw.replace(/^(?:Error|TypeError|RangeError):\s*/i, ""));
  }
}

const api = {
  auth: { login:(u:string,p:string)=>invoke("auth:login",u,p), logout:async()=>{const result=await invoke("auth:logout");try{await invoke("whatsapp:invalidateAuth");}catch{}return result;}, currentUser:()=>invoke("auth:currentUser"), changePassword:(id:number,p:string)=>invoke("auth:changePassword",id,p), setupStatus:()=>invoke("auth:setupStatus"), createInitialAdministrator:(u:string,n:string,p:string)=>invoke("auth:createInitialAdministrator",u,n,p), verifyAdminPassword:(p:string,action?:string,detail?:string)=>invoke("auth:verifyAdminPassword",p,action||"",detail||"") },
  families: { list:(f?:any)=>invoke("families:list",f), get:(id:number)=>invoke("families:get",id), create:(d:any)=>invoke("families:create",d), update:(id:number,d:any)=>invoke("families:update",id,d), archive:(id:number,r:string)=>invoke("security:archiveFamily",id,r), restore:(id:number,r?:string)=>invoke("security:restoreFamily",id,r||""), history:(id:number)=>invoke("security:familyHistory",id), createFromMembers:(ids:number[],d:any,h:number,r:string)=>invoke("security:createFamilyFromMembers",ids,d,h,r), saveSurveyForm:()=>invoke("families:saveSurveyForm") },
  members: { list:(f?:any)=>invoke("members:list",f), get:(id:number)=>invoke("members:get",id), create:(d:any)=>invoke("members:create",d), update:(id:number,d:any)=>invoke("members:update",id,d), archive:(id:number,r:string)=>invoke("security:archiveMember",id,r), restore:(id:number,r?:string)=>invoke("security:restoreMember",id,r||""), history:(id:number)=>invoke("security:memberHistory",id), move:(ids:number[],fid:number,r:string)=>invoke("security:moveMembers",ids,fid,r,"ExistingFamily"), moveHistory:(id:number)=>invoke("security:memberMoveHistory",id), relationships:()=>invoke("members:relationships"), relations:(id:number)=>invoke("members:relations",id) },
  subscriptions: { list:(f?:any)=>invoke("subscriptions:list",f), get:(id:number)=>invoke("subscriptions:get",id), create:(d:any)=>invoke("subscriptions:create",d), update:(id:number,d:any)=>invoke("subscriptions:update",id,d), remove:(id:number)=>invoke("subscriptions:remove",id), cancelPayment:(id:number,r:string,pw:string)=>invoke("subscriptions:cancelPayment",id,r,pw), paymentsHistory:(fid:number)=>invoke("subscriptions:paymentsHistory",fid), markOverdue:()=>invoke("subscriptions:markOverdue"), totalCollected:()=>invoke("subscriptions:totalCollected"), totalPending:()=>invoke("subscriptions:totalPending"), plans:()=>invoke("subscriptions:plans"),ensureCurrentMonth:()=>invoke("subscriptions:ensureCurrentMonth") },
  donations: { list:(f?:any)=>invoke("donations:list",f), get:(id:number)=>invoke("donations:get",id), create:(d:any)=>invoke("donations:create",d), update:(id:number,d:any,pw:string,r:string)=>invoke("donations:update",id,d,pw||"",r||""), remove:(id:number)=>invoke("donations:remove",id), categories:()=>invoke("donations:categories"), categoriesAll:()=>invoke("donations:categoriesAll"), createCategory:(n:string,d?:string)=>invoke("donations:createCategory",n,d||""), updateCategory:(id:number,n:string,d?:string)=>invoke("donations:updateCategory",id,n,d||""), setCategoryActive:(id:number,a:boolean)=>invoke("donations:setCategoryActive",id,a), removeCategory:(id:number)=>invoke("donations:removeCategory",id), memberBalance:(fid:number,mid?:number)=>invoke("donations:memberBalance",fid,mid), totalThisMonth:()=>invoke("donations:totalThisMonth") },
  whatsapp: { status:()=>invoke("whatsapp:status"), connect:(opts?:{acknowledged?:boolean})=>invoke("whatsapp:connect",opts||{}), ackToS:()=>invoke("whatsapp:ackToS"), qr:()=>invoke("whatsapp:qr"), disconnect:()=>invoke("whatsapp:disconnect"), unlink:()=>invoke("whatsapp:unlink"), checkNumber:(phone:string)=>invoke("whatsapp:checkNumber",phone), setFamily:(familyId:number,phone:string,enabled:boolean)=>invoke("whatsapp:setFamily",familyId,phone,enabled), getFamily:(familyId:number)=>invoke("whatsapp:getFamily",familyId), sendMessage:(input:any)=>invoke("whatsapp:sendMessage",input), sendDonationReceipt:(donationId:number,adminPassword?:string)=>invoke("whatsapp:sendDonationReceipt",donationId,adminPassword||undefined), sendSubscriptionReceipt:(subscriptionId:number,adminPassword?:string)=>invoke("whatsapp:sendSubscriptionReceipt",subscriptionId,adminPassword||undefined), recipientStats:(type:"ANNOUNCEMENT"|"SUBSCRIPTION_REMINDER")=>invoke("whatsapp:recipientStats",type), createSubscriptionCampaign:()=>invoke("whatsapp:createSubscriptionCampaign"), createAnnouncementCampaign:(text:string)=>invoke("whatsapp:createAnnouncementCampaign",text), runCampaign:(id:number)=>invoke("whatsapp:runCampaign",id), getCampaign:(id:number)=>invoke("whatsapp:getCampaign",id), listCampaigns:(limit?:number)=>invoke("whatsapp:listCampaigns",limit||30), listHistory:(limit?:number)=>invoke("whatsapp:listHistory",limit||100), retryFailed:(id:number)=>invoke("whatsapp:retryFailed",id), runtimeState:()=>invoke("whatsapp:runtimeState") },
  accounting: { list:(f?:any)=>invoke("accounting:list",f), get:(id:number)=>invoke("accounting:get",id), create:(d:any)=>invoke("accounting:create",d), update:(id:number,d:any,pw:string,r:string)=>invoke("accounting:update",id,d,pw||"",r||""), remove:(id:number)=>invoke("accounting:remove",id), void:(id:number,r:string,pw:string)=>invoke("accounting:void",id,r,pw||""), receiptSequence:()=>invoke("accounting:receiptSequence"), totalIncome:()=>invoke("accounting:totalIncome"), totalExpense:()=>invoke("accounting:totalExpense"), balance:()=>invoke("accounting:balance"), unifiedList:(f?:any)=>invoke("accounting:unifiedList",f), unifiedSummary:(f?:any)=>invoke("accounting:unifiedSummary",f), detail:(source:string,id:number)=>invoke("accounting:detail",source,id), exportPdf:(f?:any)=>invoke("accounting:exportPdf",f), exportExcel:(f?:any)=>invoke("accounting:exportExcel",f), exportAuditPack:(y:number)=>invoke("accounting:exportAuditPack",y) },
  assets: { list:(f?:any)=>invoke("assets:list",f), get:(id:number)=>invoke("assets:get",id), create:(d:any)=>invoke("assets:create",d), update:(id:number,d:any)=>invoke("assets:update",id,d), remove:(id:number)=>invoke("assets:remove",id), options:()=>invoke("assets:options"), summary:()=>invoke("assets:summary"), statement:(id:number)=>invoke("assets:statement",id) },
  marriages: { list:(f?:any)=>invoke("marriages:list",f), get:(id:number)=>invoke("marriages:get",id), create:(d:any)=>invoke("marriages:create",d), update:(id:number,d:any)=>invoke("marriages:update",id,d), remove:(id:number)=>invoke("marriages:remove",id), printRegister:()=>invoke("marriages:registerPdf") },
  deaths: { list:(f?:any)=>invoke("deaths:list",f), get:(id:number)=>invoke("deaths:get",id), create:(d:any)=>invoke("deaths:create",d), update:(id:number,d:any)=>invoke("deaths:update",id,d), remove:(id:number)=>invoke("deaths:remove",id), printRegister:()=>invoke("deaths:registerPdf") },
  welfare: { list:(f?:any)=>invoke("welfare:list",f), get:(id:number)=>invoke("welfare:get",id), create:(d:any)=>invoke("welfare:create",d), update:(id:number,d:any)=>invoke("welfare:update",id,d), approve:(id:number,a:number,r:string,md?:string)=>invoke("welfare:approve",id,a,r,md||""), reject:(id:number,r:string)=>invoke("welfare:reject",id,r), disburse:(id:number,r?:string,pw?:string)=>invoke("welfare:disburse",id,r||"",pw||""), remove:(id:number)=>invoke("welfare:remove",id), categories:()=>invoke("welfare:categories") },
  certificates: { list:(f?:any)=>invoke("certificates:list",f), issueMembership:(c:string)=>invoke("certificates:issueMembership",c), issueResidence:(f:string,i:string)=>invoke("certificates:issueResidence",f,i), issueMarriage:(m:string)=>invoke("certificates:issueMarriage",m), issueMarriageNoc:(m:string)=>invoke("certificates:issueMarriageNoc",m), issueDeath:(d:string)=>invoke("certificates:issueDeath",d), remove:(id:number)=>invoke("certificates:remove",id), generatePdf:(id:number)=>invoke("certificates:generatePdf",id), previewHtml:(id:number)=>invoke("certificates:previewHtml",id), verify:(code:string)=>invoke("certificates:verify",code), verifyQr:(payload:string)=>invoke("certificates:verifyQr",payload) },
  pdf: { generate:(h:string,n:string)=>invoke("pdf:generate",h,n), getAnekFontCss:()=>invoke("pdf:getAnekFontCss") },
  receipts: { getDonationPdf:(id:number)=>invoke("receipts:getDonationPdf",id), getSubscriptionPdf:(subscriptionId:number)=>invoke("receipts:getSubscriptionPdf",subscriptionId), saveDonationPdf:(id:number)=>invoke("receipts:saveDonationPdf",id), saveSubscriptionPdf:(subscriptionId:number)=>invoke("receipts:saveSubscriptionPdf",subscriptionId), saveDonationBatchPdf:(ids:number[])=>invoke("receipts:saveDonationBatchPdf",ids), saveSubscriptionBatchPdf:(subscriptionIds:number[])=>invoke("receipts:saveSubscriptionBatchPdf",subscriptionIds) },
  users: { list:()=>invoke("users:list"), create:(d:any)=>invoke("users:create",d), update:(id:number,d:any)=>invoke("users:update",id,d), toggleLock:(id:number,l:boolean)=>invoke("users:toggleLock",id,l), resetPassword:(id:number,p:string)=>invoke("users:resetPassword",id,p), remove:(id:number)=>invoke("users:remove",id) },
  audit: { list:(f?:any)=>invoke("audit:list",f), verify:()=>invoke("audit:verify") },
  approvals: { list:()=>invoke("approvals:list"), pendingCount:()=>invoke("approvals:pendingCount"), approve:(kind:string,id:number)=>invoke("approvals:approve",kind,id), reject:(kind:string,id:number,reason:string)=>invoke("approvals:reject",kind,id,reason||"") },
  settings: { load:()=>invoke("settings:load"), save:(d:any)=>invoke("settings:save",d) },
  app: { info:()=>invoke("app:info") },
  updates: { status:()=>invoke("updates:status"), checkNow:()=>invoke("updates:checkNow"), openReleasePage:()=>invoke("updates:openReleasePage"), openDownload:()=>invoke("updates:openDownload"), downloadUpdate:()=>invoke("updates:downloadUpdate"), installUpdate:()=>invoke("updates:installUpdate") },
  dashboard: { summary:()=>invoke("dashboard:summary"), incomeThisMonth:()=>invoke("dashboard:incomeThisMonth"), expenseThisMonth:()=>invoke("dashboard:expenseThisMonth"), balance:()=>invoke("dashboard:balance"), monthlyCollections:(m?:number)=>invoke("dashboard:monthlyCollections",m), monthlyDonations:(m?:number)=>invoke("dashboard:monthlyDonations",m), incomeVsExpense:(m?:number)=>invoke("dashboard:incomeVsExpense",m), recentActivity:(l?:number)=>invoke("dashboard:recentActivity",l), alerts:()=>invoke("dashboard:alerts"), todayAtGlance:()=>invoke("dashboard:todayAtGlance") },
  backup: { create:(d?:string)=>invoke("backup:create",d), list:()=>invoke("backup:list"), verify:(f:string)=>invoke("backup:verify",f), restore:(f:string)=>invoke("backup:restore",f), chooseMirrorDir:()=>invoke("backup:chooseMirrorDir") },
  dialog: { showSave:(n:string,f:any[])=>invoke("dialog:showSave",n,f) },
  win: { minimize:()=>invoke("win:minimize"), maximize:()=>invoke("win:maximize"), close:()=>invoke("win:close"), confirmClose:()=>invoke("win:confirm-close"), onAskClose:(cb:()=>void)=>{ const l=()=>cb(); ipcRenderer.on("win:ask-close-confirm", l); return ()=>{ ipcRenderer.removeListener("win:ask-close-confirm", l); }; } },
  uninstall: { dbStatus:()=>invoke("uninstall:dbStatus"), verify:(p:string)=>invoke("uninstall:verify",p), finish:(ok:boolean)=>invoke("uninstall:finish",ok) },
  tokens: { listEvents:()=>invoke("tokens:listEvents"), getEvent:(id:number)=>invoke("tokens:getEvent",id), createEvent:(d:any)=>invoke("tokens:createEvent",d), updateEvent:(id:number,d:any)=>invoke("tokens:updateEvent",id,d),removeEvent:(id:number,reason:string)=>invoke("tokens:removeEvent",id,reason), list:(f?:any)=>invoke("tokens:list",f), checkExisting:(id:number)=>invoke("tokens:checkExisting",id), generate:(id:number,fs:number[])=>invoke("tokens:generate",id,fs), collect:(id:number)=>invoke("tokens:collect",id), cancel:(id:number,r:string)=>invoke("tokens:cancel",id,r), replace:(id:number,r:string)=>invoke("tokens:replace",id,r), remove:(id:number,r:string)=>invoke("tokens:remove",id,r), stats:(id:number)=>invoke("tokens:stats",id), listForPdf:(id:number)=>invoke("tokens:listForPdf",id), generateTokenPdf:(id:number)=>invoke("tokens:generateTokenPdf",id), generateCollectionSheet:(id:number)=>invoke("tokens:generateCollectionSheet",id) },
  staff: {
    list: (f?: any) => invoke("staff:list", f),
    get: (id: number) => invoke("staff:get", id),
    roles: () => invoke("staff:roles"),
    create: (d: any) => invoke("staff:create", d),
    update: (id: number, d: any) => invoke("staff:update", id, d),
    archive: (id: number, reason: string) => invoke("staff:archive", id, reason),
    setStatus: (id: number, status: "Resigned" | "Expelled", effectiveDate: string, reason: string, adminPassword: string) => invoke("staff:setStatus", id, status, effectiveDate, reason, adminPassword),
    restore: (id: number, adminPassword?: string) => invoke("staff:restore", id, adminPassword),
    history: (id: number) => invoke("staff:history", id),
    listPayments: (f?: any) => invoke("staff:listPayments", f),
    paySalary: (d: any) => invoke("staff:paySalary", d),
    cancelPayment: (id: number, reason?: string, adminPassword?: string) => invoke("staff:cancelPayment", id, reason || "", adminPassword || ""),
    salarySummary: (year?: number) => invoke("staff:salarySummary", year)
  },
  committee: {
    list: (f?: any) => invoke("committee:list", f),
    get: (id: number) => invoke("committee:get", id),
    positions: () => invoke("committee:positions"),
    types: () => invoke("committee:types"),
    summary: () => invoke("committee:summary"),
    create: (d: any) => invoke("committee:create", d),
    update: (id: number, d: any, adminPassword?: string, reason?: string) => invoke("committee:update", id, d, adminPassword, reason),
    archive: (id: number, reason: string, adminPassword?: string) => invoke("committee:archive", id, reason, adminPassword),
    restore: (id: number, adminPassword?: string) => invoke("committee:restore", id, adminPassword),
    history: (id: number) => invoke("committee:history", id)
  },
  events: { onDownloadFailed: (cb: (name: string) => void) => { const h = (_e: unknown, name: string) => cb(String(name)); ipcRenderer.on("download:failed", h); return () => { ipcRenderer.removeListener("download:failed", h); }; }, onUpdateAvailable: (cb: (info: { latestVersion: string; url: string; downloadUrl?: string | null; currentVersion: string }) => void) => { const h = (_e: unknown, info: any) => cb(info); ipcRenderer.on("update:available", h); return () => { ipcRenderer.removeListener("update:available", h); }; }, onUpdateProgress: (cb: (p: { percent: number; transferred: number; total: number; bytesPerSecond: number }) => void) => { const h = (_e: unknown, p: any) => cb(p); ipcRenderer.on("update:progress", h); return () => { ipcRenderer.removeListener("update:progress", h); }; }, onUpdateDownloaded: (cb: (v: { version: string }) => void) => { const h = (_e: unknown, v: any) => cb(v); ipcRenderer.on("update:downloaded", h); return () => { ipcRenderer.removeListener("update:downloaded", h); }; }, onUpdateDownloadFailed: (cb: (r: { reason: string }) => void) => { const h = (_e: unknown, r: any) => cb(r); ipcRenderer.on("update:download-failed", h); return () => { ipcRenderer.removeListener("update:download-failed", h); }; } }
};

contextBridge.exposeInMainWorld("mms", api);
export type MmsApi = typeof api;
