import { contextBridge, ipcRenderer } from "electron";

const api = {
  auth: { login:(u:string,p:string)=>ipcRenderer.invoke("auth:login",u,p), logout:async()=>{const result=await ipcRenderer.invoke("auth:logout");try{await ipcRenderer.invoke("whatsapp:invalidateAuth");}catch{}return result;}, currentUser:()=>ipcRenderer.invoke("auth:currentUser"), changePassword:(id:number,p:string)=>ipcRenderer.invoke("auth:changePassword",id,p), setupStatus:()=>ipcRenderer.invoke("auth:setupStatus"), createInitialAdministrator:(u:string,n:string,p:string)=>ipcRenderer.invoke("auth:createInitialAdministrator",u,n,p), verifyAdminPassword:(p:string,action?:string,detail?:string)=>ipcRenderer.invoke("auth:verifyAdminPassword",p,action||"",detail||"") },
  families: { list:(f?:any)=>ipcRenderer.invoke("families:list",f), get:(id:number)=>ipcRenderer.invoke("families:get",id), create:(d:any)=>ipcRenderer.invoke("families:create",d), update:(id:number,d:any)=>ipcRenderer.invoke("families:update",id,d), archive:(id:number,r:string)=>ipcRenderer.invoke("security:archiveFamily",id,r), restore:(id:number,r?:string)=>ipcRenderer.invoke("security:restoreFamily",id,r||""), history:(id:number)=>ipcRenderer.invoke("security:familyHistory",id), createFromMembers:(ids:number[],d:any,h:number,r:string)=>ipcRenderer.invoke("security:createFamilyFromMembers",ids,d,h,r) },
  members: { list:(f?:any)=>ipcRenderer.invoke("members:list",f), get:(id:number)=>ipcRenderer.invoke("members:get",id), create:(d:any)=>ipcRenderer.invoke("members:create",d), update:(id:number,d:any)=>ipcRenderer.invoke("members:update",id,d), archive:(id:number,r:string)=>ipcRenderer.invoke("security:archiveMember",id,r), restore:(id:number,r?:string)=>ipcRenderer.invoke("security:restoreMember",id,r||""), history:(id:number)=>ipcRenderer.invoke("security:memberHistory",id), move:(ids:number[],fid:number,r:string)=>ipcRenderer.invoke("security:moveMembers",ids,fid,r,"ExistingFamily"), moveHistory:(id:number)=>ipcRenderer.invoke("security:memberMoveHistory",id), relationships:()=>ipcRenderer.invoke("members:relationships"), relations:(id:number)=>ipcRenderer.invoke("members:relations",id) },
  subscriptions: { list:(f?:any)=>ipcRenderer.invoke("subscriptions:list",f), get:(id:number)=>ipcRenderer.invoke("subscriptions:get",id), create:(d:any)=>ipcRenderer.invoke("subscriptions:create",d), update:(id:number,d:any)=>ipcRenderer.invoke("subscriptions:update",id,d), remove:(id:number)=>ipcRenderer.invoke("subscriptions:remove",id), cancelPayment:(id:number,r:string)=>ipcRenderer.invoke("subscriptions:cancelPayment",id,r), paymentsHistory:(fid:number)=>ipcRenderer.invoke("subscriptions:paymentsHistory",fid), markOverdue:()=>ipcRenderer.invoke("subscriptions:markOverdue"), totalCollected:()=>ipcRenderer.invoke("subscriptions:totalCollected"), totalPending:()=>ipcRenderer.invoke("subscriptions:totalPending"), plans:()=>ipcRenderer.invoke("subscriptions:plans"),ensureCurrentMonth:()=>ipcRenderer.invoke("subscriptions:ensureCurrentMonth") },
  donations: { list:(f?:any)=>ipcRenderer.invoke("donations:list",f), get:(id:number)=>ipcRenderer.invoke("donations:get",id), create:(d:any)=>ipcRenderer.invoke("donations:create",d), update:(id:number,d:any)=>ipcRenderer.invoke("donations:update",id,d), remove:(id:number)=>ipcRenderer.invoke("donations:remove",id), categories:()=>ipcRenderer.invoke("donations:categories"), categoriesAll:()=>ipcRenderer.invoke("donations:categoriesAll"), createCategory:(n:string,d?:string)=>ipcRenderer.invoke("donations:createCategory",n,d||""), updateCategory:(id:number,n:string,d?:string)=>ipcRenderer.invoke("donations:updateCategory",id,n,d||""), setCategoryActive:(id:number,a:boolean)=>ipcRenderer.invoke("donations:setCategoryActive",id,a), removeCategory:(id:number)=>ipcRenderer.invoke("donations:removeCategory",id), memberBalance:(fid:number,mid?:number)=>ipcRenderer.invoke("donations:memberBalance",fid,mid), totalThisMonth:()=>ipcRenderer.invoke("donations:totalThisMonth") },
  whatsapp: { status:()=>ipcRenderer.invoke("whatsapp:status"), connect:()=>ipcRenderer.invoke("whatsapp:connect"), qr:()=>ipcRenderer.invoke("whatsapp:qr"), disconnect:()=>ipcRenderer.invoke("whatsapp:disconnect"), unlink:()=>ipcRenderer.invoke("whatsapp:unlink"), checkNumber:(phone:string)=>ipcRenderer.invoke("whatsapp:checkNumber",phone), setFamily:(familyId:number,phone:string,enabled:boolean)=>ipcRenderer.invoke("whatsapp:setFamily",familyId,phone,enabled), getFamily:(familyId:number)=>ipcRenderer.invoke("whatsapp:getFamily",familyId), sendMessage:(input:any)=>ipcRenderer.invoke("whatsapp:sendMessage",input), sendDonationReceipt:(donationId:number)=>ipcRenderer.invoke("whatsapp:sendDonationReceipt",donationId), sendSubscriptionReceipt:(subscriptionId:number)=>ipcRenderer.invoke("whatsapp:sendSubscriptionReceipt",subscriptionId), recipientStats:(type:"ANNOUNCEMENT"|"SUBSCRIPTION_REMINDER")=>ipcRenderer.invoke("whatsapp:recipientStats",type), createSubscriptionCampaign:()=>ipcRenderer.invoke("whatsapp:createSubscriptionCampaign"), createAnnouncementCampaign:(text:string)=>ipcRenderer.invoke("whatsapp:createAnnouncementCampaign",text), runCampaign:(id:number)=>ipcRenderer.invoke("whatsapp:runCampaign",id), getCampaign:(id:number)=>ipcRenderer.invoke("whatsapp:getCampaign",id), listCampaigns:(limit?:number)=>ipcRenderer.invoke("whatsapp:listCampaigns",limit||30), listHistory:(limit?:number)=>ipcRenderer.invoke("whatsapp:listHistory",limit||100), retryFailed:(id:number)=>ipcRenderer.invoke("whatsapp:retryFailed",id), runtimeState:()=>ipcRenderer.invoke("whatsapp:runtimeState") },
  accounting: { list:(f?:any)=>ipcRenderer.invoke("accounting:list",f), get:(id:number)=>ipcRenderer.invoke("accounting:get",id), create:(d:any)=>ipcRenderer.invoke("accounting:create",d), update:(id:number,d:any)=>ipcRenderer.invoke("accounting:update",id,d), remove:(id:number)=>ipcRenderer.invoke("accounting:remove",id), void:(id:number,r:string)=>ipcRenderer.invoke("accounting:void",id,r), receiptSequence:()=>ipcRenderer.invoke("accounting:receiptSequence"), totalIncome:()=>ipcRenderer.invoke("accounting:totalIncome"), totalExpense:()=>ipcRenderer.invoke("accounting:totalExpense"), balance:()=>ipcRenderer.invoke("accounting:balance"), unifiedList:(f?:any)=>ipcRenderer.invoke("accounting:unifiedList",f), unifiedSummary:(f?:any)=>ipcRenderer.invoke("accounting:unifiedSummary",f), exportPdf:(f?:any)=>ipcRenderer.invoke("accounting:exportPdf",f), exportExcel:(f?:any)=>ipcRenderer.invoke("accounting:exportExcel",f), exportAuditPack:(y:number)=>ipcRenderer.invoke("accounting:exportAuditPack",y) },
  marriages: { list:(f?:any)=>ipcRenderer.invoke("marriages:list",f), get:(id:number)=>ipcRenderer.invoke("marriages:get",id), create:(d:any)=>ipcRenderer.invoke("marriages:create",d), update:(id:number,d:any)=>ipcRenderer.invoke("marriages:update",id,d), remove:(id:number)=>ipcRenderer.invoke("marriages:remove",id), printRegister:()=>ipcRenderer.invoke("marriages:registerPdf") },
  deaths: { list:(f?:any)=>ipcRenderer.invoke("deaths:list",f), get:(id:number)=>ipcRenderer.invoke("deaths:get",id), create:(d:any)=>ipcRenderer.invoke("deaths:create",d), update:(id:number,d:any)=>ipcRenderer.invoke("deaths:update",id,d), remove:(id:number)=>ipcRenderer.invoke("deaths:remove",id), printRegister:()=>ipcRenderer.invoke("deaths:registerPdf") },
  welfare: { list:(f?:any)=>ipcRenderer.invoke("welfare:list",f), get:(id:number)=>ipcRenderer.invoke("welfare:get",id), create:(d:any)=>ipcRenderer.invoke("welfare:create",d), update:(id:number,d:any)=>ipcRenderer.invoke("welfare:update",id,d), approve:(id:number,a:number,r:string,md?:string)=>ipcRenderer.invoke("welfare:approve",id,a,r,md||""), reject:(id:number,r:string)=>ipcRenderer.invoke("welfare:reject",id,r), disburse:(id:number,r?:string)=>ipcRenderer.invoke("welfare:disburse",id,r||""), remove:(id:number)=>ipcRenderer.invoke("welfare:remove",id), categories:()=>ipcRenderer.invoke("welfare:categories") },
  certificates: { list:(f?:any)=>ipcRenderer.invoke("certificates:list",f), issueMembership:(c:string)=>ipcRenderer.invoke("certificates:issueMembership",c), issueResidence:(f:string,i:string)=>ipcRenderer.invoke("certificates:issueResidence",f,i), issueMarriage:(m:string)=>ipcRenderer.invoke("certificates:issueMarriage",m), issueMarriageNoc:(m:string)=>ipcRenderer.invoke("certificates:issueMarriageNoc",m), issueDeath:(d:string)=>ipcRenderer.invoke("certificates:issueDeath",d), remove:(id:number)=>ipcRenderer.invoke("certificates:remove",id), generatePdf:(id:number)=>ipcRenderer.invoke("certificates:generatePdf",id), previewHtml:(id:number)=>ipcRenderer.invoke("certificates:previewHtml",id), verify:(code:string)=>ipcRenderer.invoke("certificates:verify",code), verifyQr:(payload:string)=>ipcRenderer.invoke("certificates:verifyQr",payload) },
  pdf: { generate:(h:string,n:string)=>ipcRenderer.invoke("pdf:generate",h,n), getAnekFontCss:()=>ipcRenderer.invoke("pdf:getAnekFontCss") },
  receipts: { getDonationPdf:(id:number)=>ipcRenderer.invoke("receipts:getDonationPdf",id), getSubscriptionPdf:(subscriptionId:number)=>ipcRenderer.invoke("receipts:getSubscriptionPdf",subscriptionId), saveDonationPdf:(id:number)=>ipcRenderer.invoke("receipts:saveDonationPdf",id), saveSubscriptionPdf:(subscriptionId:number)=>ipcRenderer.invoke("receipts:saveSubscriptionPdf",subscriptionId), saveDonationBatchPdf:(ids:number[])=>ipcRenderer.invoke("receipts:saveDonationBatchPdf",ids), saveSubscriptionBatchPdf:(subscriptionIds:number[])=>ipcRenderer.invoke("receipts:saveSubscriptionBatchPdf",subscriptionIds) },
  users: { list:()=>ipcRenderer.invoke("users:list"), create:(d:any)=>ipcRenderer.invoke("users:create",d), update:(id:number,d:any)=>ipcRenderer.invoke("users:update",id,d), toggleLock:(id:number,l:boolean)=>ipcRenderer.invoke("users:toggleLock",id,l), resetPassword:(id:number,p:string)=>ipcRenderer.invoke("users:resetPassword",id,p), remove:(id:number)=>ipcRenderer.invoke("users:remove",id) },
  audit: { list:(f?:any)=>ipcRenderer.invoke("audit:list",f), verify:()=>ipcRenderer.invoke("audit:verify") },
  settings: { load:()=>ipcRenderer.invoke("settings:load"), save:(d:any)=>ipcRenderer.invoke("settings:save",d) },
  dashboard: { summary:()=>ipcRenderer.invoke("dashboard:summary"), incomeThisMonth:()=>ipcRenderer.invoke("dashboard:incomeThisMonth"), expenseThisMonth:()=>ipcRenderer.invoke("dashboard:expenseThisMonth"), balance:()=>ipcRenderer.invoke("dashboard:balance"), monthlyCollections:(m?:number)=>ipcRenderer.invoke("dashboard:monthlyCollections",m), monthlyDonations:(m?:number)=>ipcRenderer.invoke("dashboard:monthlyDonations",m), incomeVsExpense:(m?:number)=>ipcRenderer.invoke("dashboard:incomeVsExpense",m), recentActivity:(l?:number)=>ipcRenderer.invoke("dashboard:recentActivity",l), alerts:()=>ipcRenderer.invoke("dashboard:alerts"), todayAtGlance:()=>ipcRenderer.invoke("dashboard:todayAtGlance") },
  backup: { create:(d?:string)=>ipcRenderer.invoke("backup:create",d), list:()=>ipcRenderer.invoke("backup:list"), verify:(f:string)=>ipcRenderer.invoke("backup:verify",f), restore:(f:string)=>ipcRenderer.invoke("backup:restore",f) },
  dialog: { showSave:(n:string,f:any[])=>ipcRenderer.invoke("dialog:showSave",n,f) },
  win: { minimize:()=>ipcRenderer.invoke("win:minimize"), maximize:()=>ipcRenderer.invoke("win:maximize"), close:()=>ipcRenderer.invoke("win:close") },
  tokens: { listEvents:()=>ipcRenderer.invoke("tokens:listEvents"), getEvent:(id:number)=>ipcRenderer.invoke("tokens:getEvent",id), createEvent:(d:any)=>ipcRenderer.invoke("tokens:createEvent",d), updateEvent:(id:number,d:any)=>ipcRenderer.invoke("tokens:updateEvent",id,d),removeEvent:(id:number)=>ipcRenderer.invoke("tokens:removeEvent",id),  list:(f?:any)=>ipcRenderer.invoke("tokens:list",f), checkExisting:(id:number)=>ipcRenderer.invoke("tokens:checkExisting",id), generate:(id:number,fs:number[])=>ipcRenderer.invoke("tokens:generate",id,fs), collect:(id:number)=>ipcRenderer.invoke("tokens:collect",id), cancel:(id:number,r:string)=>ipcRenderer.invoke("tokens:cancel",id,r), replace:(id:number,r:string)=>ipcRenderer.invoke("tokens:replace",id,r), remove:(id:number,r:string)=>ipcRenderer.invoke("tokens:remove",id,r), stats:(id:number)=>ipcRenderer.invoke("tokens:stats",id), listForPdf:(id:number)=>ipcRenderer.invoke("tokens:listForPdf",id), generateTokenPdf:(id:number)=>ipcRenderer.invoke("tokens:generateTokenPdf",id), generateCollectionSheet:(id:number)=>ipcRenderer.invoke("tokens:generateCollectionSheet",id) },
  staff: {
    list: (f?: any) => ipcRenderer.invoke("staff:list", f),
    get: (id: number) => ipcRenderer.invoke("staff:get", id),
    roles: () => ipcRenderer.invoke("staff:roles"),
    create: (d: any) => ipcRenderer.invoke("staff:create", d),
    update: (id: number, d: any) => ipcRenderer.invoke("staff:update", id, d),
    archive: (id: number, reason: string) => ipcRenderer.invoke("staff:archive", id, reason),
    setStatus: (id: number, status: "Resigned" | "Expelled", effectiveDate: string, reason: string) => ipcRenderer.invoke("staff:setStatus", id, status, effectiveDate, reason),
    restore: (id: number) => ipcRenderer.invoke("staff:restore", id),
    history: (id: number) => ipcRenderer.invoke("staff:history", id),
    listPayments: (f?: any) => ipcRenderer.invoke("staff:listPayments", f),
    paySalary: (d: any) => ipcRenderer.invoke("staff:paySalary", d),
    cancelPayment: (id: number, reason?: string) => ipcRenderer.invoke("staff:cancelPayment", id, reason || ""),
    salarySummary: (year?: number) => ipcRenderer.invoke("staff:salarySummary", year)
  },
  committee: {
    list: (f?: any) => ipcRenderer.invoke("committee:list", f),
    get: (id: number) => ipcRenderer.invoke("committee:get", id),
    positions: () => ipcRenderer.invoke("committee:positions"),
    types: () => ipcRenderer.invoke("committee:types"),
    summary: () => ipcRenderer.invoke("committee:summary"),
    create: (d: any) => ipcRenderer.invoke("committee:create", d),
    update: (id: number, d: any) => ipcRenderer.invoke("committee:update", id, d),
    archive: (id: number, reason: string) => ipcRenderer.invoke("committee:archive", id, reason),
    restore: (id: number) => ipcRenderer.invoke("committee:restore", id),
    history: (id: number) => ipcRenderer.invoke("committee:history", id)
  }
};

contextBridge.exposeInMainWorld("mms", api);
export type MmsApi = typeof api;
