import { app, ipcMain } from "electron";
import path from "node:path";
import * as data from "./services/data.service.js";
import { changePassword, createInitialAdministrator, needsInitialSetup } from "./services/auth.service.js";
import { security, type Actor } from "./services/security.service.js";
import { createBackup, listBackups, verifyBackup, extractVerifiedBackup } from "./services/backup.service.js";
import { closeDB, getDB } from "./db/connection.js";

type ActorProvider = () => Actor | null;
function register(name: string, handler: (...args: any[]) => any) { try { ipcMain.removeHandler(name); } catch {} ipcMain.handle(name, async (_event, ...args) => handler(...args)); }
function validatePassword(password: string) { if (!password || password.length < 8) throw new Error("Password must be at least 8 characters"); if (!/[A-Z]/.test(password) || !/[a-z]/.test(password) || !/\d/.test(password) || !/[^A-Za-z0-9]/.test(password)) throw new Error("Password must include uppercase, lowercase, digit, and special character"); }

export function registerSecurityIpc(getActor: ActorProvider) {
  register("auth:setupStatus", () => ({ required: needsInitialSetup() }));
  register("auth:createInitialAdministrator", (username: string, fullName: string, password: string) => { const user = createInitialAdministrator(username, fullName, password); try { data.audit.log(user.id, user.username, "INITIAL_SETUP", "auth", user.id, "Initial Administrator account created", ""); } catch {} return { success: true, user }; });
  const actor = (): Actor => { const current=getActor(); if(current)return current; const authActor=(globalThis as any).__mmsGetActor?.() as Actor|null|undefined; if(authActor)return authActor; throw new Error("Authentication is required for this operation"); };
  const admin = (): Actor => { const current=actor(); if(current.role!=="Administrator")throw new Error("Administrator permission is required for this operation"); return current; };
  register("auth:changePassword",(userId:number,newPassword:string)=>{const a=actor();if(userId!==a.id&&a.role!=="Administrator")throw new Error("You can only change your own password");validatePassword(newPassword);changePassword(userId,newPassword);try{data.audit.log(a.id,a.username,"PASSWORD_CHANGE","auth",userId,"Password changed","");}catch{}return{success:true};});
  register("families:update",(id:number,d:any)=>security.updateFamily(actor(),id,d)); register("members:update",(id:number,d:any)=>security.updateMember(actor(),id,d));
  register("families:remove",()=>{throw new Error("Families cannot be permanently deleted. Archive the family instead.");}); register("members:remove",()=>{throw new Error("Members cannot be permanently deleted. Archive the member instead.");}); register("marriages:remove",()=>{throw new Error("Marriage records cannot be permanently deleted. Correct or revoke the record instead.");}); register("deaths:remove",()=>{throw new Error("Death records cannot be permanently deleted. Correct or revoke the record instead.");}); register("certificates:remove",()=>{throw new Error("Issued certificates cannot be permanently deleted. Revoke the certificate instead.");});
  register("families:create",(d:any)=>{actor();return data.families.create(d);}); register("members:create",(d:any)=>{actor();return data.members.create(d);});
  register("subscriptions:create",(d:any)=>{const a=actor();return data.subscriptions.create({...d,collectedBy:a.id});}); register("subscriptions:update",(id:number,d:any)=>{actor();return data.subscriptions.update(id,d);}); register("subscriptions:remove",()=>{admin();throw new Error("Financial records cannot be permanently deleted. Use a correction/reversal instead.");}); register("subscriptions:markOverdue",()=>{actor();return data.subscriptions.markOverdue();});
  register("donations:create",(d:any)=>{const a=actor();return data.donations.create({...d,receivedBy:a.id});}); register("donations:update",(id:number,d:any)=>{actor();return data.donations.update(id,d);}); register("donations:remove",()=>{admin();throw new Error("Financial records cannot be permanently deleted. Use a correction/reversal instead.");});
  register("accounting:create",(d:any)=>{const a=actor();return data.accounting.create({...d,createdBy:a.id});}); register("accounting:update",(id:number,d:any)=>{actor();return data.accounting.update(id,d);}); register("accounting:remove",()=>{admin();throw new Error("Financial records cannot be permanently deleted. Use a correction/reversal instead.");});
  register("marriages:create",(d:any)=>{const a=actor();return data.marriages.create({...d,createdBy:a.id});}); register("marriages:update",(id:number,d:any)=>{actor();return data.marriages.update(id,d);}); register("deaths:create",(d:any)=>{const a=actor();return data.deaths.create({...d,createdBy:a.id});}); register("deaths:update",(id:number,d:any)=>{actor();return data.deaths.update(id,d);});
  register("welfare:create",(d:any)=>{const a=actor();return data.welfare.create({...d,createdBy:a.id});}); register("welfare:update",(id:number,d:any)=>{actor();return data.welfare.update(id,d);}); register("welfare:approve",(id:number,amount:number,remarks:string)=>{const a=admin();return data.welfare.approve(id,amount,remarks,a.id);}); register("welfare:reject",(id:number,reason:string)=>{const a=admin();return data.welfare.reject(id,reason,a.id);}); register("welfare:disburse",(id:number)=>{const a=admin();return data.welfare.disburse(id,a.id);}); register("welfare:remove",()=>{admin();throw new Error("Welfare records cannot be permanently deleted. Correct or revoke the record instead.");});
  register("certificates:issueMembership",(code:string)=>data.certificates.issueMembership(code,actor().id)); register("certificates:issueResidence",(familyNum:string,issuedTo:string)=>data.certificates.issueResidence(familyNum,issuedTo,actor().id)); register("certificates:issueMarriage",(marriageNum:string)=>data.certificates.issueMarriage(marriageNum,actor().id)); register("certificates:issueMarriageNoc",(marriageNum:string)=>data.certificates.issueMarriageNoc(marriageNum,actor().id)); register("certificates:issueDeath",(deathNum:string)=>data.certificates.issueDeath(deathNum,actor().id));
  register("users:list",()=>{admin();return data.users.list();}); register("users:create",(d:any)=>{const a=admin();validatePassword(String(d?.password??""));return data.users.create(d,a.role);}); register("users:update",(id:number,d:any)=>{admin();return data.users.update(id,d);}); register("users:toggleLock",(id:number,locked:boolean)=>{admin();return data.users.toggleLock(id,locked);}); register("users:resetPassword",(id:number,p:string)=>{const a=admin();validatePassword(p);changePassword(id,p);try{data.audit.log(a.id,a.username,"PASSWORD_RESET","users",id,"Administrator reset user password","");}catch{}return{success:true};}); register("users:remove",(id:number)=>{admin();return data.users.remove(id);});
  register("audit:list",(filter:any)=>{actor();return data.audit.list(filter||{});}); register("settings:save",(d:any)=>{const a=admin();return data.settings.save({...d,updatedBy:a.id});});
  register("tokens:createEvent",(d:any)=>{actor();return data.tokens.createEvent(d);}); register("tokens:updateEvent",(id:number,d:any)=>{actor();return data.tokens.updateEvent(id,d);}); register("tokens:generate",(eventId:number,familyIds:number[])=>data.tokens.generate(eventId,familyIds,actor().id)); register("tokens:collect",(tokenId:number)=>data.tokens.collect(tokenId,actor().id)); register("tokens:cancel",(tokenId:number,reason:string)=>{actor();return data.tokens.cancel(tokenId,reason);}); register("tokens:replace",(tokenId:number,reason:string)=>data.tokens.replace(tokenId,reason,actor().id));
  register("tokens:remove",(tokenId:number,reason:string)=>{const a=admin();if(!Number.isInteger(tokenId)||tokenId<=0)throw new Error("Invalid token");if(!reason?.trim())throw new Error("A deletion reason is required");const db=getDB();const token=db.prepare(`SELECT ta.id,ta.token_code,ta.status,ta.event_id,ta.family_id,te.event_name,te.event_date,te.event_time,f.family_number FROM token_assignments ta JOIN token_events te ON te.id=ta.event_id LEFT JOIN families f ON f.id=ta.family_id WHERE ta.id=?`).get(tokenId) as any;if(!token)throw new Error("Token not found");const eventDate=String(token.event_date||"");const eventTime=String(token.event_time||"").trim();if(!eventDate)throw new Error("Token event has no valid date");const eventMoment=eventTime?new Date(`${eventDate}T${/^\d{2}:\d{2}$/.test(eventTime)?`${eventTime}:00`:eventTime}`):new Date(`${eventDate}T23:59:59`);if(Number.isNaN(eventMoment.getTime())||eventMoment>=new Date())throw new Error("Tokens can only be deleted after the event has ended");const tx=db.transaction(()=>{const metadata=JSON.stringify({tokenCode:token.token_code,eventId:token.event_id,eventName:token.event_name,eventDate:token.event_date,eventTime:token.event_time||null,familyId:token.family_id,familyNumber:token.family_number||null,previousStatus:token.status,deletionType:"temporary_token_after_event"});db.prepare(`INSERT INTO audit_log (user_id,username,action,module,entity_id,description,metadata,created_at) VALUES (?, ?, 'DELETE', 'tokens', ?, ?, ?, datetime('now'))`).run(a.id,a.username,token.id,`Temporary token ${token.token_code} deleted after event ${token.event_name}`,metadata);db.prepare("DELETE FROM token_assignments WHERE id=?").run(token.id);});tx();return{success:true,tokenId:token.id};});
  register("security:archiveFamily",(id:number,reason:string)=>security.archiveFamily(actor(),id,reason)); register("security:restoreFamily",(id:number,reason?:string)=>security.restoreFamily(actor(),id,reason||"")); register("security:archiveMember",(id:number,reason:string)=>security.archiveMember(actor(),id,reason)); register("security:restoreMember",(id:number,reason?:string)=>security.restoreMember(actor(),id,reason||"")); register("security:familyHistory",(id:number,limit?:number)=>security.history("family",id,limit||100)); register("security:memberHistory",(id:number,limit?:number)=>security.history("member",id,limit||100)); register("security:memberMoveHistory",(id:number)=>security.familyMoveHistory(id)); register("security:moveMembers",(ids:number[],familyId:number,reason:string,moveType?:"ExistingFamily"|"NewFamily")=>security.moveMembers(actor(),ids,familyId,reason,moveType||"ExistingFamily")); register("security:createFamilyFromMembers",(ids:number[],familyData:any,headMemberId:number,reason:string)=>security.createFamilyFromMembers(actor(),ids,familyData,headMemberId,reason));
  register("backup:create",async(destination?:string)=>{admin();const file=destination||path.join(app.getPath("userData"),`backup-${new Date().toISOString().replace(/[:.]/g,"-")}.mmbak`);return createBackup(file);}); register("backup:list",()=>{actor();return{success:true,backups:listBackups(app.getPath("userData"))};}); register("backup:verify",(file:string)=>{actor();return verifyBackup(file);}); register("backup:restore",(file:string)=>{admin();const current=path.join(app.getPath("userData"),`pre-restore-backup-${Date.now()}.mmbak`);createBackup(current);const target=path.join(app.getPath("userData"),"mms.db");closeDB();extractVerifiedBackup(file,target);app.relaunch();app.exit(0);return{success:true};});
}
