import { useEffect,useState } from "react";
import { Database,FileArchive,RefreshCw,ShieldCheck,RotateCcw,Loader2 } from "lucide-react";
import { useI18n } from "@/i18n";
import { Button,Dialog,Label,Input } from "@/components/ui";
import { toast } from "@/lib/toast";
import { formatDateTime } from "@/lib/utils";
interface BackupRecord{name:string;path:string;size:number;time:string;valid?:boolean}
const fmt=(n:number)=>{if(!n)return "—";let v=n,i=0;const u=["B","KB","MB","GB"];while(v>=1024&&i<u.length-1){v/=1024;i++;}return `${v.toFixed(v<10&&i>0?1:0)} ${u[i]}`};
export function Backup(){const {t,isMalayalam}=useI18n();const tx=(en:string,ml:string)=>isMalayalam()?ml:en;const [backups,setBackups]=useState<BackupRecord[]>([]);const [loading,setLoading]=useState(false);const [creating,setCreating]=useState(false);const [restoreOpen,setRestoreOpen]=useState(false);const [restorePath,setRestorePath]=useState("");
 const refresh=async()=>{setLoading(true);try{const r:any=await window.mms.backup.list();setBackups(r.backups||[]);}catch(e:any){toast.error(e.message);}finally{setLoading(false)}};useEffect(()=>{refresh()},[]);
 const create=async()=>{setCreating(true);try{const r:any=await window.mms.backup.create();if(r?.success===false){if(r.error!=="cancelled")throw new Error(r.error);return;}toast.success(tx("Verified backup created","പരിശോധിച്ച ബാക്കപ്പ് സൃഷ്ടിച്ചു"));await refresh();}catch(e:any){toast.error(e.message||t("tb_backup_failed"));}finally{setCreating(false)}};
 const verify=async(p:string)=>{try{await window.mms.backup.verify(p);toast.success(tx("Backup integrity verified","ബാക്കപ്പ് സമഗ്രത പരിശോധിച്ചു"));}catch(e:any){toast.error(e.message)}};
 const restore=async()=>{if(!restorePath.trim())return;try{await window.mms.backup.verify(restorePath);await window.mms.backup.restore(restorePath);toast.success(tx("Restore started. The application will restart.","റസ്റ്റോർ ആരംഭിച്ചു. ആപ്ലിക്കേഷൻ പുനരാരംഭിക്കും."));}catch(e:any){toast.error(e.message)}};
 return <div className="view view-enter"><div className="vhead"><div className="modic t-em"><Database size={20}/></div><div><h1>{t("bak_title")}</h1><div className="vs">{t("bak_subtitle")}</div></div><div className="vr"><Button variant="secondary" onClick={refresh} disabled={loading}><RefreshCw size={14}/>{t("action_refresh")}</Button><Button onClick={create} disabled={creating}>{creating?<Loader2 size={14} className="animate-spin"/>:<FileArchive size={14}/>} {creating?t("ui_saving"):t("bak_create_now")}</Button></div></div>
 <div className="stat-grid stat-grid-3"><div className="stat t-em"><div className="val">{backups.length}</div><div className="slab">{t("bak_total_backups")}</div></div><div className="stat t-gold"><div className="val val-sm">{backups[0]?formatDateTime(backups[0].time):"—"}</div><div className="slab">{t("bak_most_recent")}</div></div><div className="stat t-sky"><div className="val val-sm">{backups[0]?.valid===false?tx("Invalid","അസാധു"):tx("Verified","പരിശോധിച്ചു")}</div><div className="slab">{t("bak_health")}</div></div></div>
 <div className="card card-pad-tight"><div className="ch-head mb-2"><div><div className="ch-title">{t("bak_recent")}</div><div className="ch-sub">{tx("Integrity-checked snapshots","സമഗ്രത പരിശോധിച്ച സ്നാപ്ഷോട്ടുകൾ")}</div></div><Button variant="secondary" onClick={()=>setRestoreOpen(true)} disabled={!backups.length}><RotateCcw size={14}/>{tx("Restore backup","ബാക്കപ്പ് റസ്റ്റോർ")}</Button></div><div className="tbl tbl-flat"><table><thead><tr><th>{t("bak_name_col")}</th><th>{t("tok_date")}</th><th>{t("bak_size_col")}</th><th>{tx("Integrity","സമഗ്രത")}</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan={5} className="tempty"><Loader2 size={16} className="animate-spin"/></td></tr>:backups.length===0?<tr><td colSpan={5} className="tempty">{t("bak_no_backups")}</td></tr>:backups.map(b=><tr key={b.path}><td><span className="bk-cell-name">{b.name}</span></td><td>{formatDateTime(b.time)}</td><td><span className="count-chip">{fmt(b.size)}</span></td><td>{b.valid===false?<span className="text-danger">{tx("Invalid","അസാധു")}</span>:<span className="text-success"><ShieldCheck size={14}/></span>}</td><td><Button variant="secondary" onClick={()=>verify(b.path)}><ShieldCheck size={14}/>{tx("Verify","പരിശോധിക്കുക")}</Button></td></tr>)}</tbody></table></div></div>
 <div className="card card-pad-5 mt-3"><div className="ch-title">{tx("Safe restore","സുരക്ഷിത റസ്റ്റോർ")}</div><div className="ch-sub mt-1">{tx("A fresh pre-restore backup is created automatically. The selected backup is integrity-checked before replacement and the application restarts afterward.","റസ്റ്റോറിന് മുമ്പ് നിലവിലെ ഡാറ്റയുടെ ബാക്കപ്പ് സ്വയമേവ എടുക്കും. തിരഞ്ഞെടുക്കുന്ന ബാക്കപ്പ് പരിശോധിച്ച ശേഷമേ ഡാറ്റ മാറ്റുകയുള്ളൂ; തുടർന്ന് ആപ്ലിക്കേഷൻ പുനരാരംഭിക്കും.")}</div></div>
 <Dialog open={restoreOpen} onClose={()=>setRestoreOpen(false)} title={tx("Restore backup","ബാക്കപ്പ് റസ്റ്റോർ")}><div className="p-6 space-y-4"><Label>{tx("Backup file path","ബാക്കപ്പ് ഫയൽ പാത")}</Label><Input value={restorePath} onChange={e=>setRestorePath(e.target.value)} placeholder="C:\\...\\backup-....mmbak"/><p className="text-sm text-muted">{tx("This action requires Administrator permission and will restart the application.","ഈ പ്രവർത്തനത്തിന് അഡ്മിനിസ്ട്രേറ്റർ അനുമതി ആവശ്യമാണ്; ആപ്ലിക്കേഷൻ പുനരാരംഭിക്കും.")}</p><div className="flex justify-end gap-2"><Button variant="secondary" onClick={()=>setRestoreOpen(false)}>{t("action_cancel")}</Button><Button onClick={restore}>{tx("Verify & Restore","പരിശോധിച്ച് റസ്റ്റോർ ചെയ്യുക")}</Button></div></div></Dialog>
 </div>}
