import { useEffect, useState } from "react";
import { Plus, Edit2, Eye, Flower2, Users, Award } from "lucide-react";
import { useI18n } from "@/i18n";
import { useList } from "@/hooks/useList";
import { Button, Dialog, Input, Label, Select, Textarea, Badge } from "@/components/ui";
import { DataTable, type Column } from "@/components/DataTable";
import { toast } from "@/lib/toast";
import { formatDate } from "@/lib/utils";
interface Death { id:number; death_number:string; deceased_name:string; father_name:string; gender:string; date_of_death:string; burial_date:string; cause_of_death:string; burial_place:string; family_id:number; remarks:string; }
interface Member { id:number; name:string; gender:string; family_id:number; family_number?:string; house_name?:string; address?:string; father_name?:string; }
const emptyForm:Partial<Death>={death_number:"",deceased_name:"",father_name:"",gender:"Male",date_of_death:"",burial_date:"",cause_of_death:"",burial_place:"",family_id:0,remarks:""};
const codeFontStyle="code-text-sm";
export function Deaths(){
 const {t,lang}=useI18n(); const ml=lang==="ml"; const [search,setSearch]=useState(""); const [dialogOpen,setDialogOpen]=useState(false); const [editingId,setEditingId]=useState<number|null>(null); const [form,setForm]=useState<Partial<Death>>(emptyForm); const [previewOpen,setPreviewOpen]=useState(false); const [previewRow,setPreviewRow]=useState<Death|null>(null); const [fromMahallu,setFromMahallu]=useState(false); const [memberId,setMemberId]=useState(""); const [members,setMembers]=useState<Member[]>([]);
 const {rows,total,totalPages,loading,refetch,page,setPage}=useList((filter)=>window.mms.deaths.list(filter),{pageSize:20});
 useEffect(()=>{window.mms.members.list({page:1,pageSize:10000,status:"Active"}).then(r=>setMembers(r.rows||[])).catch(()=>{});},[]);
 const selectMember=async(id:string)=>{setMemberId(id); if(!id)return; try{const m=await window.mms.members.get(Number(id)); if(!m)return; setForm(v=>({...v,deceased_name:m.name||"",gender:m.gender||"Male",family_id:m.family_id,father_name:""}));}catch{const m=members.find(x=>String(x.id)===id); if(m)setForm(v=>({...v,deceased_name:m.name,gender:m.gender,family_id:m.family_id,father_name:""}));}};
 const resetForm=()=>{setForm(emptyForm);setEditingId(null);setFromMahallu(false);setMemberId("");setDialogOpen(true);};
 const handleSave=async()=>{if(!form.deceased_name||!form.date_of_death){toast.error(t("ui_deceased_date_required"));return;}try{const payload:any={deceasedName:form.deceased_name,fatherName:form.father_name||"",gender:form.gender||"Male",dateOfDeath:form.date_of_death,burialDate:form.burial_date||"",causeOfDeath:form.cause_of_death||"",burialPlace:form.burial_place||"",familyId:form.family_id||null,remarks:form.remarks||"",createdBy:1};if(editingId)await window.mms.deaths.update(editingId,payload);else await window.mms.deaths.create(payload);toast.success(editingId?t("ui_save_changes"):t("ui_death_added"));setDialogOpen(false);refetch();}catch(err:any){toast.error(err.message||t("ui_failed_save"));}};
 const handleEdit=async(id:number)=>{const d=await window.mms.deaths.get(id);setForm(d||emptyForm);setEditingId(id);setFromMahallu(false);setMemberId("");setDialogOpen(true);};
 const handleRowDoubleClick=(row:Death)=>{setPreviewRow(row);setPreviewOpen(true);}; const switchToEdit=async()=>{if(!previewRow)return;const id=previewRow.id;setPreviewOpen(false);await handleEdit(id);};
 const columns:Column<Death>[]=[{header:t("dth_number"),accessor:r=><span className={codeFontStyle+" text-primary"}>{r.death_number}</span>},{header:t("dth_deceased"),accessor:r=><span className="font-medium">{r.deceased_name}</span>},{header:t("member_gender"),accessor:r=>r.gender},{header:t("dth_date_of_death"),accessor:r=>formatDate(r.date_of_death)},{header:t("dth_burial_date"),accessor:r=>formatDate(r.burial_date)},{header:t("dth_burial_place"),accessor:r=>r.burial_place||"—"},{header:"",accessor:r=><div className="flex items-center gap-1 justify-end"><button className="act-btn act-edit" onClick={()=>handleEdit(r.id)}><Edit2 className="h-4 w-4"/></button></div>,align:"right"}];
 const previewDetails=previewRow?[{k:t("dth_number"),v:previewRow.death_number},{k:t("dth_deceased"),v:previewRow.deceased_name},{k:t("dth_father"),v:previewRow.father_name||"—"},{k:t("member_gender"),v:previewRow.gender||"—"},{k:t("dth_date_of_death"),v:formatDate(previewRow.date_of_death)},{k:t("dth_burial_date"),v:formatDate(previewRow.burial_date)},{k:t("dth_burial_place"),v:previewRow.burial_place||"—"},{k:t("dth_cause"),v:previewRow.cause_of_death||"—",full:true},{k:t("ui_remarks"),v:previewRow.remarks||"—",full:true}]:[];
 return <div className="view view-enter"><div className="vhead"><div className="modic t-em"><Flower2 size={20}/></div><div><h1>{t("dth_title")}</h1><div className="vs">{t("dth_subtitle")}</div></div><div className="vr"><Button onClick={resetForm}><Plus className="h-4 w-4"/>{t("ui_add_record")}</Button></div></div>
 <DataTable columns={columns} rows={rows as Death[]} loading={loading} total={total} page={page} pageSize={20} totalPages={totalPages} onPageChange={setPage} searchValue={search} onSearchChange={setSearch} rowKey={r=>r.id} onRowDoubleClick={handleRowDoubleClick}/>
 <Dialog open={previewOpen} onClose={()=>setPreviewOpen(false)} title={t("dth_title")}><div className="dlg-pad">{previewRow&&<><div className="dlg-hero t-em"><div className="dlg-hero-ic"><Eye size={20}/></div><div className="dlg-hero-body"><div className="dlg-hero-title">{previewRow.deceased_name}</div><div className="dlg-hero-sub">{previewRow.death_number} · {formatDate(previewRow.date_of_death)}</div></div><Badge variant="muted">{previewRow.gender||"—"}</Badge></div><div className="det-grid">{previewDetails.map((d,i)=><div key={i} className={`det${d.full?" full":""}`}><span className="k">{d.k}</span><span className="v">{d.v}</span></div>)}</div></>}<div className="dlg-actions"><Button variant="secondary" onClick={()=>setPreviewOpen(false)}>{t("ui_close")}</Button><Button onClick={switchToEdit}><Edit2 size={14}/>{t("action_edit")}</Button><Button variant="secondary" onClick={async()=>{if(!previewRow)return;try{await window.mms.certificates.issueDeath(previewRow.death_number);toast.success(t("ui_cert_issued"));}catch(e:any){toast.error(e.message);}}}><Award size={14}/>{t("ui_generate_cert")}</Button></div></div></Dialog>
 <Dialog open={dialogOpen} onClose={()=>setDialogOpen(false)} title={editingId?t("action_edit"):t("ui_add_record")} className="max-w-2xl"><div className="p-6 space-y-4"><div className="flex items-center gap-2 mb-1"><input type="checkbox" checked={fromMahallu} onChange={e=>{setFromMahallu(e.target.checked);if(!e.target.checked)setMemberId("")}}/><span className="text-sm">{ml?"മരണപ്പെട്ട വ്യക്തി ഈ മഹല്ലിലെ അംഗമാണ്":"Deceased is from this Mahallu"}</span></div>{fromMahallu&&<div><Label><Users size={14} className="inline"/> {ml?"അംഗത്തെ തിരഞ്ഞെടുക്കുക":"Select member"}</Label><Select value={memberId} onChange={e=>selectMember(e.target.value)}><option value="">{t("ui_select")}</option>{members.map(m=><option key={m.id} value={m.id}>{m.name} · {m.house_name||m.family_number||""}</option>)}</Select></div>}<div className="grid grid-cols-2 gap-4"><div><Label>{t("dth_deceased")} *</Label><Input value={form.deceased_name||""} readOnly={fromMahallu} onChange={e=>setForm({...form,deceased_name:e.target.value})}/></div><div><Label>{t("dth_father")}</Label><Input value={form.father_name||""} readOnly={fromMahallu} onChange={e=>setForm({...form,father_name:e.target.value})}/></div><div><Label>{t("member_gender")}</Label><Select value={form.gender||"Male"} disabled={fromMahallu} onChange={e=>setForm({...form,gender:e.target.value})}><option value="Male">{t("gender_male")}</option><option value="Female">{t("gender_female")}</option><option value="Other">{t("gender_other")}</option></Select></div><div><Label>{t("dth_date_of_death")} *</Label><Input type="date" value={form.date_of_death||""} onChange={e=>setForm({...form,date_of_death:e.target.value})}/></div><div><Label>{t("dth_burial_date")}</Label><Input type="date" value={form.burial_date||""} onChange={e=>setForm({...form,burial_date:e.target.value})}/></div><div><Label>{t("dth_burial_place")}</Label><Input value={form.burial_place||""} onChange={e=>setForm({...form,burial_place:e.target.value})}/></div><div className="col-span-2"><Label>{t("dth_cause")}</Label><Textarea rows={2} value={form.cause_of_death||""} onChange={e=>setForm({...form,cause_of_death:e.target.value})}/></div></div><div className="flex justify-end gap-2 pt-2"><Button variant="secondary" onClick={()=>setDialogOpen(false)}>{t("action_cancel")}</Button><Button onClick={handleSave}>{t("action_save")}</Button></div></div></Dialog>
 </div>;
}
