import { useEffect, useState } from "react";
import { Plus, Edit2, Eye, Heart, Users, Award } from "lucide-react";
import { useI18n } from "@/i18n";
import { useList } from "@/hooks/useList";
import { Button, Dialog, Input, Label, Textarea, SectionLabel, Badge, Select } from "@/components/ui";
import { DataTable, type Column } from "@/components/DataTable";
import { toast } from "@/lib/toast";
import { formatDate } from "@/lib/utils";

interface Marriage { id:number; marriage_number:string; nikah_date:string; registration_date:string; bride_name:string; bride_father:string; bride_address:string; groom_name:string; groom_father:string; groom_address:string; witness1:string; witness2:string; witness3:string; witness4:string; mahar:string; place:string; remarks:string; }
interface Member { id:number; name:string; gender:string; father_name?:string; relationship?:string; is_head?:number; family_number?:string; house_name?:string; address?:string; mobile?:string; family_id:number; }
interface Family { id:number; family_number:string; house_name:string; area?:string; address?:string; status:string; }
const emptyForm:Partial<Marriage>={marriage_number:"",nikah_date:"",registration_date:"",bride_name:"",bride_father:"",bride_address:"",groom_name:"",groom_father:"",groom_address:"",witness1:"",witness2:"",witness3:"",witness4:"",mahar:"",place:"",remarks:""};
const codeFontStyle="code-text-sm";

export function Marriages(){
 const {t,lang}=useI18n(); const ml=lang==="ml";
 const [search,setSearch]=useState(""); const [dialogOpen,setDialogOpen]=useState(false); const [editingId,setEditingId]=useState<number|null>(null); const [form,setForm]=useState<Partial<Marriage>>(emptyForm); const [previewOpen,setPreviewOpen]=useState(false); const [previewRow,setPreviewRow]=useState<Marriage|null>(null);
 const [families,setFamilies]=useState<Family[]>([]);
 const [brideFromMahallu,setBrideFromMahallu]=useState(false); const [groomFromMahallu,setGroomFromMahallu]=useState(false);
 const [brideFamilyId,setBrideFamilyId]=useState(""); const [brideMemberId,setBrideMemberId]=useState(""); const [brideMembers,setBrideMembers]=useState<Member[]>([]);
 const [groomFamilyId,setGroomFamilyId]=useState(""); const [groomMemberId,setGroomMemberId]=useState(""); const [groomMembers,setGroomMembers]=useState<Member[]>([]);
 const {rows,total,totalPages,loading,refetch,page,setPage}=useList((filter)=>window.mms.marriages.list(filter),{pageSize:20});
 useEffect(()=>{window.mms.families.list({pageSize:5000}).then(r=>setFamilies((r.rows||[]).filter((f:Family)=>f.status!=="Archived"))).catch(()=>{});},[]);
 // Cascading: loading members of the chosen family (bride side).
 useEffect(()=>{ if(!brideFamilyId){setBrideMembers([]);return;} window.mms.members.list({familyId:Number(brideFamilyId),status:"Active",pageSize:1000}).then(r=>setBrideMembers((r.rows||[]).filter((m:Member)=>m.gender==="Female"))).catch(()=>setBrideMembers([])); },[brideFamilyId]);
 // Cascading: loading members of the chosen family (groom side).
 useEffect(()=>{ if(!groomFamilyId){setGroomMembers([]);return;} window.mms.members.list({familyId:Number(groomFamilyId),status:"Active",pageSize:1000}).then(r=>setGroomMembers((r.rows||[]).filter((m:Member)=>m.gender==="Male"))).catch(()=>setGroomMembers([])); },[groomFamilyId]);
 // Father derivation: explicit father_name first; for a head's Son/Daughter the
 // male family head is the father. Fallback: empty (user fills manually).
 const deriveFather=(m:Member,familyMembers:Member[]):string=>{ if(m.father_name) return m.father_name; if(m.relationship==="Son"||m.relationship==="Daughter"){ const head=familyMembers.find(x=>x.is_head===1&&x.gender==="Male")||familyMembers.find(x=>x.relationship==="Head"&&x.gender==="Male"); if(head&&head.id!==m.id) return head.name; } return ""; };
 const selectBride=async(id:string)=>{ setBrideMemberId(id); if(!id){return;} try{ const m=await window.mms.members.get(Number(id)); if(!m)return; const f=m.family_id?await window.mms.families.get(m.family_id):null; const famMembers=brideMembers.length?brideMembers:[]; setForm(v=>({...v,bride_name:m.name||"",bride_father:deriveFather(m,famMembers),bride_address:f?[f.house_name,f.area,f.address].filter(Boolean).join(", "):""})); }catch{ const m=brideMembers.find(x=>String(x.id)===id); if(m)setForm(v=>({...v,bride_name:m.name,bride_father:deriveFather(m,brideMembers),bride_address:""})); } };
 const selectGroom=async(id:string)=>{ setGroomMemberId(id); if(!id){return;} try{ const m=await window.mms.members.get(Number(id)); if(!m)return; const f=m.family_id?await window.mms.families.get(m.family_id):null; setForm(v=>({...v,groom_name:m.name||"",groom_father:deriveFather(m,groomMembers),groom_address:f?[f.house_name,f.area,f.address].filter(Boolean).join(", "):""})); }catch{ const m=groomMembers.find(x=>String(x.id)===id); if(m)setForm(v=>({...v,groom_name:m.name,groom_father:deriveFather(m,groomMembers),groom_address:""})); } };
 const resetForm=()=>{setForm(emptyForm);setEditingId(null);setBrideFromMahallu(false);setGroomFromMahallu(false);setBrideFamilyId("");setBrideMemberId("");setBrideMembers([]);setGroomFamilyId("");setGroomMemberId("");setGroomMembers([]);setDialogOpen(true);};
 const handleSave=async()=>{if(!form.bride_name||!form.groom_name||!form.nikah_date){toast.error(t("ui_bride_groom_date_required"));return;}try{const payload:any={brideName:form.bride_name,brideFather:form.bride_father||"",brideAddress:form.bride_address||"",groomName:form.groom_name,groomFather:form.groom_father||"",groomAddress:form.groom_address||"",witness1:form.witness1||"",witness2:form.witness2||"",witness3:form.witness3||"",witness4:form.witness4||"",mahar:form.mahar||"",nikahDate:form.nikah_date,registrationDate:form.registration_date||"",place:form.place||"",remarks:form.remarks||"",createdBy:1}; if(editingId){await window.mms.marriages.update(editingId,payload);toast.success(t("ui_save_changes"));}else{await window.mms.marriages.create(payload);toast.success(t("mrg_register"));}setDialogOpen(false);refetch();}catch(err:any){toast.error(err.message||t("ui_failed_save"));}};
 const handleEdit=async(id:number)=>{const m=await window.mms.marriages.get(id);setForm(m||emptyForm);setEditingId(id);setBrideFromMahallu(false);setGroomFromMahallu(false);setBrideFamilyId("");setBrideMemberId("");setBrideMembers([]);setGroomFamilyId("");setGroomMemberId("");setGroomMembers([]);setDialogOpen(true);};
 const handleRowDoubleClick=(row:Marriage)=>{setPreviewRow(row);setPreviewOpen(true);}; const switchToEdit=async()=>{if(!previewRow)return;const id=previewRow.id;setPreviewOpen(false);await handleEdit(id);};
 const columns:Column<Marriage>[]=[{header:t("mrg_number"),accessor:r=><span className={codeFontStyle+" text-primary"}>{r.marriage_number}</span>},{header:t("mrg_nikah_date"),accessor:r=>formatDate(r.nikah_date)},{header:t("mrg_bride"),accessor:r=><span className="font-medium">{r.bride_name}</span>},{header:t("mrg_groom"),accessor:r=><span className="font-medium">{r.groom_name}</span>},{header:t("mrg_place"),accessor:r=>r.place||"—"},{header:"",accessor:r=><div className="flex items-center gap-1 justify-end"><button className="act-btn act-edit" onClick={()=>handleEdit(r.id)}><Edit2 className="h-4 w-4"/></button></div>,align:"right"}];
 const previewDetails=previewRow?[{k:t("mrg_number"),v:previewRow.marriage_number},{k:t("mrg_nikah_date"),v:formatDate(previewRow.nikah_date)},{k:t("mrg_registration_date"),v:formatDate(previewRow.registration_date)},{k:t("mrg_place"),v:previewRow.place||"—"},{k:t("mrg_mahar"),v:previewRow.mahar||"—"},{k:t("mrg_bride"),v:previewRow.bride_name},{k:t("mrg_bride_father"),v:previewRow.bride_father||"—"},{k:t("mrg_groom"),v:previewRow.groom_name},{k:t("mrg_groom_father"),v:previewRow.groom_father||"—"},{k:`${t("ui_witness_n")} 1`,v:previewRow.witness1||"—"},{k:`${t("ui_witness_n")} 2`,v:previewRow.witness2||"—"},{k:`${t("ui_witness_n")} 3`,v:previewRow.witness3||"—"},{k:`${t("ui_witness_n")} 4`,v:previewRow.witness4||"—"},{k:t("ui_bride_address"),v:previewRow.bride_address||"—",full:true},{k:t("ui_groom_address"),v:previewRow.groom_address||"—",full:true}]:[];
 return <div className="view view-enter"><div className="vhead"><div className="modic t-em"><Heart size={20}/></div><div><h1>{t("mrg_title")}</h1><div className="vs">{t("mrg_subtitle")}</div></div><div className="vr"><Button onClick={resetForm}><Plus className="h-4 w-4"/>{t("mrg_register")}</Button></div></div>
 <DataTable columns={columns} rows={rows as Marriage[]} loading={loading} total={total} page={page} pageSize={20} totalPages={totalPages} onPageChange={setPage} searchValue={search} onSearchChange={setSearch} rowKey={r=>r.id} onRowDoubleClick={handleRowDoubleClick}/>
 <Dialog open={previewOpen} onClose={()=>setPreviewOpen(false)} title={t("mrg_title")}><div className="dlg-pad">{previewRow&&<><div className="dlg-hero t-em"><div className="dlg-hero-ic"><Heart size={20}/></div><div className="dlg-hero-body"><div className="dlg-hero-title">{previewRow.bride_name} <span className="heart-sep">♥</span> {previewRow.groom_name}</div><div className="dlg-hero-sub">{previewRow.marriage_number} · {formatDate(previewRow.nikah_date)}</div></div><Badge variant="default">{previewRow.place||"—"}</Badge></div><div className="det-grid">{previewDetails.map((d,i)=><div key={i} className={`det${d.full?" full":""}`}><span className="k">{d.k}</span><span className="v">{d.v}</span></div>)}</div></>}<div className="dlg-actions"><Button variant="secondary" onClick={()=>setPreviewOpen(false)}>{t("ui_close")}</Button><Button onClick={switchToEdit}><Edit2 size={14}/>{t("action_edit")}</Button><Button variant="secondary" onClick={async()=>{if(!previewRow)return;try{const r=await window.mms.certificates.issueMarriage(previewRow.marriage_number);toast.success(t("ui_cert_issued"));}catch(e:any){toast.error(e.message);}}}><Award size={14}/>{t("ui_generate_cert")}</Button></div></div></Dialog>
 <Dialog open={dialogOpen} onClose={()=>setDialogOpen(false)} title={editingId?t("action_edit"):t("mrg_register")} className="max-w-3xl"><div className="p-6 space-y-5">
 <div><SectionLabel>{t("mrg_bride_details")}</SectionLabel><div className="flex items-center gap-2 mb-3"><input type="checkbox" checked={brideFromMahallu} onChange={e=>{setBrideFromMahallu(e.target.checked);if(!e.target.checked){setBrideFamilyId("");setBrideMemberId("");setBrideMembers([]);}}}/><span className="text-sm">{ml?"വധു ഈ മഹല്ലിലെ അംഗമാണ്":"Bride is from this Mahallu"}</span></div>{brideFromMahallu&&<div className="mb-3 space-y-3"><div><Label><Users size={14} className="inline"/> {t("mrg_select_bride_family")}</Label><Select value={brideFamilyId} onChange={e=>{setBrideFamilyId(e.target.value);setBrideMemberId("");}}><option value="">{t("ui_select")}</option>{families.map(f=><option key={f.id} value={f.id}>{f.house_name} ({f.family_number})</option>)}</Select></div>{brideFamilyId&&<div><Label><Users size={14} className="inline"/> {t("mrg_select_bride_member")}</Label><Select value={brideMemberId} onChange={e=>selectBride(e.target.value)} disabled={!brideMembers.length}><option value="">{brideMembers.length?t("ui_select"):t("mrg_no_girls_in_family")}</option>{brideMembers.map(m=><option key={m.id} value={m.id}>{m.name}{m.relationship?` · ${m.relationship}`:""}{m.is_head?" · Head":""}</option>)}</Select></div>}</div>}<div className="grid grid-cols-2 gap-4"><div><Label>{t("mrg_bride")} *</Label><Input value={form.bride_name||""} readOnly={brideFromMahallu} onChange={e=>setForm({...form,bride_name:e.target.value})}/></div><div><Label>{t("mrg_bride_father")}</Label><Input value={form.bride_father||""} onChange={e=>setForm({...form,bride_father:e.target.value})}/></div><div className="col-span-2"><Label>{t("ui_bride_address")}</Label><Textarea rows={2} value={form.bride_address||""} onChange={e=>setForm({...form,bride_address:e.target.value})}/></div></div></div>
 <div><SectionLabel>{t("mrg_groom_details")}</SectionLabel><div className="flex items-center gap-2 mb-3"><input type="checkbox" checked={groomFromMahallu} onChange={e=>{setGroomFromMahallu(e.target.checked);if(!e.target.checked){setGroomFamilyId("");setGroomMemberId("");setGroomMembers([]);}}}/><span className="text-sm">{ml?"വരൻ ഈ മഹല്ലിലെ അംഗമാണ്":"Groom is from this Mahallu"}</span></div>{groomFromMahallu&&<div className="mb-3 space-y-3"><div><Label><Users size={14} className="inline"/> {t("mrg_select_groom_family")}</Label><Select value={groomFamilyId} onChange={e=>{setGroomFamilyId(e.target.value);setGroomMemberId("");}}><option value="">{t("ui_select")}</option>{families.map(f=><option key={f.id} value={f.id}>{f.house_name} ({f.family_number})</option>)}</Select></div>{groomFamilyId&&<div><Label><Users size={14} className="inline"/> {t("mrg_select_groom_member")}</Label><Select value={groomMemberId} onChange={e=>selectGroom(e.target.value)} disabled={!groomMembers.length}><option value="">{groomMembers.length?t("ui_select"):t("mrg_no_boys_in_family")}</option>{groomMembers.map(m=><option key={m.id} value={m.id}>{m.name}{m.relationship?` · ${m.relationship}`:""}{m.is_head?" · Head":""}</option>)}</Select></div>}</div>}<div className="grid grid-cols-2 gap-4"><div><Label>{t("mrg_groom")} *</Label><Input value={form.groom_name||""} readOnly={groomFromMahallu} onChange={e=>setForm({...form,groom_name:e.target.value})}/></div><div><Label>{t("mrg_groom_father")}</Label><Input value={form.groom_father||""} onChange={e=>setForm({...form,groom_father:e.target.value})}/></div><div className="col-span-2"><Label>{t("ui_groom_address")}</Label><Textarea rows={2} value={form.groom_address||""} onChange={e=>setForm({...form,groom_address:e.target.value})}/></div></div></div>
 <div><SectionLabel>{t("mrg_witnesses")}</SectionLabel><div className="grid grid-cols-2 gap-4">{[1,2,3,4].map(n=><div key={n}><Label>{t("ui_witness_n")} {n}</Label><Input value={(form as any)[`witness${n}`]||""} onChange={e=>setForm({...form,[`witness${n}`]:e.target.value})}/></div>)}</div></div>
 <div><SectionLabel>{t("mrg_other_details")}</SectionLabel><div className="grid grid-cols-2 gap-4"><div><Label>{t("mrg_mahar")}</Label><Input value={form.mahar||""} onChange={e=>setForm({...form,mahar:e.target.value})}/></div><div><Label>{t("mrg_place")}</Label><Input value={form.place||""} onChange={e=>setForm({...form,place:e.target.value})}/></div><div><Label>{t("mrg_nikah_date")} *</Label><Input type="date" value={form.nikah_date||""} onChange={e=>setForm({...form,nikah_date:e.target.value})}/></div><div><Label>{t("mrg_registration_date")}</Label><Input type="date" value={form.registration_date||""} onChange={e=>setForm({...form,registration_date:e.target.value})}/></div><div className="col-span-2"><Label>{t("ui_remarks")}</Label><Textarea rows={2} value={form.remarks||""} onChange={e=>setForm({...form,remarks:e.target.value})}/></div></div></div>
 <div className="flex justify-end gap-2 pt-2"><Button variant="secondary" onClick={()=>setDialogOpen(false)}>{t("action_cancel")}</Button><Button onClick={handleSave}>{t("action_save")}</Button></div></div></Dialog>
 </div>;
}
