import { useEffect, useState } from "react";
import { Plus, Edit2, Eye, Archive, RotateCcw, History, MoveRight, Home } from "lucide-react";
import { useI18n } from "@/i18n";
import { useList } from "@/hooks/useList";
import { Button, Dialog, Input, Label, Select, Textarea, Badge } from "@/components/ui";
import { DataTable, type Column } from "@/components/DataTable";
import { toast } from "@/lib/toast";
import { statusVariant, formatDate } from "@/lib/utils";

interface Member { id:number; member_code:string; name:string; gender:string; date_of_birth:string; age:number; blood_group:string; occupation:string; education:string; marital_status:string; mobile:string; email:string; emergency_contact?:string; relationship:string; status:string; nationality:string; address:string; family_id:number; family_number?:string; house_name?:string; archive_state?:number; }
interface Family { id:number; family_number:string; house_name:string; status:string; }
interface HistoryRow { id:number; changed_at:string; action:string; username:string; summary:string; changes_json:string; reason:string; }
const emptyForm:Partial<Member>={name:"",gender:"Male",date_of_birth:"",age:0,blood_group:"",occupation:"",education:"",marital_status:"Single",mobile:"",email:"",emergency_contact:"",relationship:"Head",status:"Active",nationality:"",address:"",family_id:0};

export function Members(){
 const {t,isMalayalam}=useI18n(); const tx=(en:string,ml:string)=>isMalayalam()?ml:en;
 const [search,setSearch]=useState(""); const [familyFilter,setFamilyFilter]=useState("All"); const [statusFilter,setStatusFilter]=useState("All"); const [page,setPage]=useState(1); const [families,setFamilies]=useState<Family[]>([]);
 const [dialogOpen,setDialogOpen]=useState(false); const [editingId,setEditingId]=useState<number|null>(null); const [form,setForm]=useState<Partial<Member>>(emptyForm);
 const [previewOpen,setPreviewOpen]=useState(false); const [preview,setPreview]=useState<Member|null>(null); const [history,setHistory]=useState<HistoryRow[]>([]); const [moveHistory,setMoveHistory]=useState<any[]>([]);
 const [securityOpen,setSecurityOpen]=useState(false); const [securityAction,setSecurityAction]=useState<"archive"|"restore"|"move"|"newFamily"|null>(null); const [reason,setReason]=useState(""); const [targetFamily,setTargetFamily]=useState(""); const [newFamily,setNewFamily]=useState({houseName:"",houseNumber:"",ward:"",area:"",address:"",pincode:"",phone:"",altPhone:"",notes:""});
 const {rows,total,totalPages,loading,refetch,setFilters}=useList((filter)=>window.mms.members.list(filter),{pageSize:20,initialFilters:{status:"All",familyId:"All"}});
 useEffect(()=>{window.mms.families.list({pageSize:1000}).then(r=>setFamilies(r.rows||[])).catch(()=>{});},[]); useEffect(()=>{setFilters({status:statusFilter,familyId:familyFilter});},[statusFilter,familyFilter,setFilters]);
 const save=async()=>{if(!form.name||!form.family_id){toast.error(t("ui_name_family_required"));return;}try{const p={familyId:form.family_id,name:form.name,arabicName:"",gender:form.gender,dateOfBirth:form.date_of_birth,age:form.age,bloodGroup:form.blood_group,occupation:form.occupation,education:form.education,maritalStatus:form.marital_status,mobile:form.mobile,email:form.email,emergencyContact:form.emergency_contact,relationship:form.relationship,status:"Active",nationality:form.nationality,address:form.address};if(editingId)await window.mms.members.update(editingId,p);else await window.mms.members.create(p);toast.success(t("ui_save_changes"));setDialogOpen(false);setEditingId(null);setForm(emptyForm);refetch();}catch(e:any){toast.error(e.message||t("ui_failed_save"));}};
 const edit=async(id:number)=>{const m=await window.mms.members.get(id);setForm(m||emptyForm);setEditingId(id);setDialogOpen(true);};
 const openPreview=async(m:Member)=>{setPreview(m);setPreviewOpen(true);try{const [h,mh]=await Promise.all([window.mms.members.history(m.id),window.mms.members.moveHistory(m.id)]);setHistory(h);setMoveHistory(mh);}catch{setHistory([]);setMoveHistory([]);}};
 const openSecurity=(a:"archive"|"restore"|"move"|"newFamily")=>{setSecurityAction(a);setReason("");setTargetFamily("");setSecurityOpen(true);};
 const execute=async()=>{if(!preview||!securityAction)return;if((securityAction==="archive"||securityAction==="move"||securityAction==="newFamily")&&!reason.trim()){toast.error(tx("A reason is required","കാരണം നൽകണം"));return;}try{if(securityAction==="archive")await window.mms.members.archive(preview.id,reason);else if(securityAction==="restore")await window.mms.members.restore(preview.id,reason);else if(securityAction==="move"){if(!targetFamily)throw new Error(tx("Select a destination family","ലക്ഷ്യ കുടുംബം തിരഞ്ഞെടുക്കുക"));await window.mms.members.move([preview.id],Number(targetFamily),reason);}else{if(!newFamily.houseName.trim())throw new Error(tx("House name is required","വീട്ടുപേര് നൽകണം"));await window.mms.families.createFromMembers([preview.id],newFamily,preview.id,reason);}toast.success(tx("Operation completed","പ്രവർത്തനം പൂർത്തിയായി"));setSecurityOpen(false);setPreviewOpen(false);refetch();}catch(e:any){toast.error(e.message);}};
 const columns:Column<Member>[]=[{header:t("member_code"),accessor:r=><span className="code-text-sm text-primary">{r.member_code}</span>,width:"120px"},{header:t("member_name"),accessor:r=><span className="font-medium">{r.name}</span>},{header:t("member_gender"),accessor:r=>r.gender},{header:t("member_age"),accessor:r=>r.age||"—"},{header:t("member_mobile"),accessor:r=>r.mobile||"—"},{header:t("member_family"),accessor:r=>r.house_name||r.family_number||"—"},{header:t("family_status"),accessor:r=><Badge variant={statusVariant(r.status)}>{r.status}</Badge>},{header:"",accessor:r=><div className="rowact"><button className="act-btn act-edit" onClick={()=>edit(r.id)} title={t("action_edit")}><Edit2 className="h-4 w-4"/></button><button className="act-btn" onClick={()=>openPreview(r)} title={tx("View / manage","കാണുക / നിയന്ത്രിക്കുക")}><Eye className="h-4 w-4"/></button></div>,align:"right"}];
 const actionTitle=securityAction==="archive"?tx("Archive member","അംഗത്തെ ആർക്കൈവ് ചെയ്യുക"):securityAction==="restore"?tx("Restore member","അംഗത്തെ പുനഃസ്ഥാപിക്കുക"):securityAction==="move"?tx("Move to existing family","നിലവിലുള്ള കുടുംബത്തിലേക്ക് മാറ്റുക"):tx("Create new family","പുതിയ കുടുംബം സൃഷ്ടിക്കുക");
 return <div className="view view-enter"><div className="vhead"><div className="modic t-em"><Home size={20}/></div><div><h1>{t("member_title")}</h1><div className="vs">{t("member_subtitle")}</div></div><div className="vr"><Button onClick={()=>{setForm(emptyForm);setEditingId(null);setDialogOpen(true)}}><Plus className="h-4 w-4"/>{t("add_member")}</Button></div></div>
 <DataTable columns={columns} rows={rows as Member[]} loading={loading} total={total} page={page} pageSize={20} totalPages={totalPages} onPageChange={setPage} searchValue={search} onSearchChange={setSearch} rowKey={r=>r.id} onRowDoubleClick={openPreview} toolbar={<div className="flex gap-2"><Select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} className="w-40"><option value="All">{tx("All","എല്ലാം")}</option><option value="Active">{tx("Active","സജീവം")}</option><option value="Archived">{tx("Archived","ആർക്കൈവ് ചെയ്തത്")}</option></Select><Select value={familyFilter} onChange={e=>setFamilyFilter(e.target.value)} className="w-48"><option value="All">{t("ui_all_families")}</option>{families.filter(f=>f.status!=="Archived").map(f=><option key={f.id} value={String(f.id)}>{f.house_name} ({f.family_number})</option>)}</Select></div>}/>
 <Dialog open={previewOpen} onClose={()=>setPreviewOpen(false)} title={t("member_title")}><div className="dlg-pad">{preview&&<><div className="dlg-hero t-em"><div className="dlg-hero-ic">{(preview.name||"?").charAt(0).toUpperCase()}</div><div className="dlg-hero-body"><div className="dlg-hero-title">{preview.name}</div><div className="dlg-hero-sub code-text-sm">{preview.member_code}</div></div><Badge variant={statusVariant(preview.status)}>{preview.status}</Badge></div><div className="det-grid">{[[t("member_code"),preview.member_code],[t("member_name"),preview.name],[t("member_family"),preview.house_name||preview.family_number||"—"],[t("member_gender"),preview.gender],[t("member_age"),String(preview.age||"—")],[t("member_dob"),formatDate(preview.date_of_birth)],[t("member_blood_group"),preview.blood_group||"—"],[t("member_occupation"),preview.occupation||"—"],[t("member_education"),preview.education||"—"],[t("member_marital_status"),preview.marital_status||"—"],[t("member_mobile"),preview.mobile||"—"],[t("member_email"),preview.email||"—"],[t("member_relationship"),preview.relationship||"—"],[t("family_status"),preview.status],[t("family_address"),preview.address||"—"]].map(([k,v],i)=><div className="det" key={i}><span className="k">{k}</span><span className="v">{v}</span></div>)}</div><div className="mt-5"><div className="flex items-center gap-2 mb-3"><History size={16}/><strong>{tx("Activity & History","പ്രവർത്തനങ്ങളും ചരിത്രവും")}</strong></div><div className="space-y-2 max-h-56 overflow-auto">{[...history,...moveHistory.map((m:any)=>({id:`m${m.id}`,changed_at:m.moved_at,action:"FAMILY_MOVE",username:m.moved_by_username,summary:`${tx("Family moved","കുടുംബം മാറ്റി")} ${m.old_family_number||""} → ${m.new_family_number||""}`,changes_json:"",reason:m.reason}))].length?[...history,...moveHistory.map((m:any)=>({id:`m${m.id}`,changed_at:m.moved_at,action:"FAMILY_MOVE",username:m.moved_by_username,summary:`${tx("Family moved","കുടുംബം മാറ്റി")} ${m.old_family_number||""} → ${m.new_family_number||""}`,changes_json:"",reason:m.reason}))].map((h:any)=><div key={h.id} className="p-3 rounded-lg border border-border"><div className="flex justify-between gap-3"><b>{h.summary}</b><span className="text-xs text-muted">{h.changed_at}</span></div><div className="text-xs text-muted mt-1">{h.username} · {h.action}{h.reason?` · ${h.reason}`:""}</div>{h.changes_json&&<pre className="text-xs mt-2 whitespace-pre-wrap">{h.changes_json}</pre>}</div>):<div className="text-sm text-muted">{tx("No history recorded","ചരിത്ര രേഖകളില്ല")}</div>}</div></div></>}
 <div className="dlg-actions"><Button variant="secondary" onClick={()=>setPreviewOpen(false)}>{t("ui_close")}</Button>{preview?.status==="Archived"?<Button onClick={()=>openSecurity("restore")}><RotateCcw size={14}/>{tx("Restore","പുനഃസ്ഥാപിക്കുക")}</Button>:<><Button onClick={()=>edit(preview!.id)}><Edit2 size={14}/>{t("action_edit")}</Button><Button variant="secondary" onClick={()=>openSecurity("archive")}><Archive size={14}/>{tx("Archive","ആർക്കൈവ്")}</Button><Button variant="secondary" onClick={()=>openSecurity("move")}><MoveRight size={14}/>{tx("Move","മാറ്റുക")}</Button><Button variant="secondary" onClick={()=>openSecurity("newFamily")}><Plus size={14}/>{tx("New family","പുതിയ കുടുംബം")}</Button></>}</div></div></Dialog>
 <Dialog open={securityOpen} onClose={()=>setSecurityOpen(false)} title={actionTitle}><div className="p-6 space-y-4">{securityAction==="archive"&&<p>{tx("The member will be removed from active lists but all history will be preserved.","അംഗത്തെ സജീവ പട്ടികയിൽ നിന്ന് മാറ്റും, എന്നാൽ മുഴുവൻ ചരിത്രവും സംരക്ഷിക്കും.")}</p>}{securityAction==="restore"&&<p>{tx("Restore this member to the active records?","ഈ അംഗത്തെ സജീവ രേഖകളിലേക്ക് പുനഃസ്ഥാപിക്കണോ?")}</p>}{securityAction==="move"&&<div><Label>{tx("Destination family","ലക്ഷ്യ കുടുംബം")} *</Label><Select value={targetFamily} onChange={e=>setTargetFamily(e.target.value)}><option value="">{t("ui_select")}</option>{families.filter(f=>f.status!=="Archived"&&f.id!==preview?.family_id).map(f=><option key={f.id} value={String(f.id)}>{f.house_name} ({f.family_number})</option>)}</Select></div>}{securityAction==="newFamily"&&<div className="grid grid-cols-2 gap-3"><div><Label>{tx("House name","വീട്ടുപേര്")} *</Label><Input value={newFamily.houseName} onChange={e=>setNewFamily({...newFamily,houseName:e.target.value})}/></div><div><Label>{tx("House number","വീട്ടുനമ്പർ")}</Label><Input value={newFamily.houseNumber} onChange={e=>setNewFamily({...newFamily,houseNumber:e.target.value})}/></div><div><Label>{tx("Ward","വാർഡ്")}</Label><Input value={newFamily.ward} onChange={e=>setNewFamily({...newFamily,ward:e.target.value})}/></div><div><Label>{tx("Area","പ്രദേശം")}</Label><Input value={newFamily.area} onChange={e=>setNewFamily({...newFamily,area:e.target.value})}/></div><div className="col-span-2"><Label>{tx("Address","വിലാസം")}</Label><Textarea rows={2} value={newFamily.address} onChange={e=>setNewFamily({...newFamily,address:e.target.value})}/></div></div>}{securityAction!=="restore"&&<div><Label>{tx("Reason","കാരണം")} *</Label><Textarea rows={2} value={reason} onChange={e=>setReason(e.target.value)}/></div>}<div className="flex justify-end gap-2"><Button variant="secondary" onClick={()=>setSecurityOpen(false)}>{t("action_cancel")}</Button><Button onClick={execute}>{actionTitle}</Button></div></div></Dialog>
 <Dialog open={dialogOpen} onClose={()=>setDialogOpen(false)} title={editingId?t("action_edit"):t("add_member")} className="max-w-3xl"><div className="p-6 space-y-4"><div className="grid grid-cols-2 gap-4"><div><Label>{t("member_family")} *</Label><Select value={form.family_id||""} onChange={e=>setForm({...form,family_id:Number(e.target.value)})}><option value="">{t("ui_select")}</option>{families.filter(f=>f.status!=="Archived").map(f=><option key={f.id} value={f.id}>{f.house_name} ({f.family_number})</option>)}</Select></div><div><Label>{t("member_name")} *</Label><Input value={form.name||""} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><Label>{t("member_gender")}</Label><Select value={form.gender||"Male"} onChange={e=>setForm({...form,gender:e.target.value})}><option>Male</option><option>Female</option><option>Other</option></Select></div><div><Label>{t("member_dob")}</Label><Input type="date" value={form.date_of_birth||""} onChange={e=>setForm({...form,date_of_birth:e.target.value})}/></div><div><Label>{t("member_age")}</Label><Input type="number" value={form.age||""} onChange={e=>setForm({...form,age:Number(e.target.value)})}/></div><div><Label>{t("member_blood_group")}</Label><Select value={form.blood_group||""} onChange={e=>setForm({...form,blood_group:e.target.value})}><option value="">—</option><option>A+</option><option>A-</option><option>B+</option><option>B-</option><option>AB+</option><option>AB-</option><option>O+</option><option>O-</option></Select></div><div><Label>{t("member_occupation")}</Label><Input value={form.occupation||""} onChange={e=>setForm({...form,occupation:e.target.value})}/></div><div><Label>{t("member_education")}</Label><Input value={form.education||""} onChange={e=>setForm({...form,education:e.target.value})}/></div><div><Label>{t("member_marital_status")}</Label><Select value={form.marital_status||"Single"} onChange={e=>setForm({...form,marital_status:e.target.value})}><option>Single</option><option>Married</option><option>Divorced</option><option>Widowed</option></Select></div><div><Label>{t("member_mobile")}</Label><Input value={form.mobile||""} onChange={e=>setForm({...form,mobile:e.target.value})}/></div><div><Label>{t("member_email")}</Label><Input value={form.email||""} onChange={e=>setForm({...form,email:e.target.value})}/></div><div><Label>{t("member_relationship")}</Label><Select value={form.relationship||"Head"} onChange={e=>setForm({...form,relationship:e.target.value})}>{["Head","Spouse","Son","Daughter","Parent","Sibling","Other"].map(x=><option key={x}>{x}</option>)}</Select></div></div><div><Label>{t("family_address")}</Label><Textarea rows={2} value={form.address||""} onChange={e=>setForm({...form,address:e.target.value})}/></div><div className="flex justify-end gap-2"><Button variant="secondary" onClick={()=>setDialogOpen(false)}>{t("action_cancel")}</Button><Button onClick={save}>{t("action_save")}</Button></div></div></Dialog>
 </div>;
}