import { useState } from "react";
import { Download, FileSpreadsheet, FileText, Home, Users, Wallet, Gift, Gem, Flower, ScrollText, ShieldCheck, BarChart3, Loader2, CalendarRange } from "lucide-react";
import { useI18n } from "@/i18n";
import { Select, Input } from "@/components/ui";
import { toast } from "@/lib/toast";

type Tint = "t-em"|"t-gold"|"t-sky"|"t-rose"|"t-vio"|"t-pink"|"t-orange"|"t-teal"|"t-blue"|"t-slate";
interface ReportType { id:string; title:string; description:string; tint:Tint; icon:any; fetch:()=>Promise<any[]>; columns?:string[]; dateKeys:string[]; }

const REPORTS:ReportType[]=[
 {id:"families",title:"Family Register",description:"All registered families with house, ward, contact and member count.",tint:"t-em",icon:Home,fetch:async()=>((await window.mms.families.list({pageSize:100000})).rows||[]),columns:["family_number","house_name","house_number","ward","area","phone","status","member_count"],dateKeys:["created_at"]},
 {id:"members",title:"Member Directory",description:"Complete member roster with demographics and contact.",tint:"t-teal",icon:Users,fetch:async()=>((await window.mms.members.list({pageSize:100000})).rows||[]),columns:["member_code","name","gender","age","blood_group","mobile","email","house_name","family_number","status"],dateKeys:["created_at"]},
 {id:"subscriptions",title:"Subscription Summary",description:"Subscription receipts, periods, payments and status.",tint:"t-gold",icon:Wallet,fetch:async()=>((await window.mms.subscriptions.list({pageSize:100000})).rows||[]),dateKeys:["payment_date","period_start","created_at"]},
 {id:"donations",title:"Donation Report",description:"Donations by donor, category, date and purpose.",tint:"t-pink",icon:Gift,fetch:async()=>((await window.mms.donations.list({pageSize:100000})).rows||[]),dateKeys:["donation_date","created_at"]},
 {id:"accounting",title:"Financial Statement",description:"Income and expense ledger transactions with totals.",tint:"t-sky",icon:BarChart3,fetch:async()=>{const [r,inc,exp,bal]=await Promise.all([window.mms.accounting.list({pageSize:100000}),window.mms.accounting.totalIncome(),window.mms.accounting.totalExpense(),window.mms.accounting.balance()]);return [...(r?.rows||[]).map((x:any)=>({date:x.txn_date||"",type:x.type,description:x.description,amount:x.amount,payment_method:x.payment_method||""})),{date:"",type:"SUMMARY",description:"TOTAL INCOME",amount:inc??0},{date:"",type:"SUMMARY",description:"TOTAL EXPENSE",amount:exp??0},{date:"",type:"SUMMARY",description:"NET BALANCE",amount:bal??0}]},dateKeys:["date","txn_date","created_at"]},
 {id:"marriages",title:"Marriage Register",description:"Nikah registrations and parties.",tint:"t-vio",icon:Gem,fetch:async()=>((await window.mms.marriages.list({pageSize:100000})).rows||[]),columns:["marriage_number","nikah_date","bride_name","groom_name","place","mahar"],dateKeys:["nikah_date","registration_date","created_at"]},
 {id:"deaths",title:"Death Register",description:"Death and burial records.",tint:"t-slate",icon:Flower,fetch:async()=>((await window.mms.deaths.list({pageSize:100000})).rows||[]),columns:["death_number","deceased_name","gender","date_of_death","burial_date","burial_place"],dateKeys:["date_of_death","burial_date","created_at"]},
 {id:"welfare",title:"Welfare Report",description:"Welfare requests and assistance status.",tint:"t-orange",icon:ShieldCheck,fetch:async()=>((await window.mms.welfare.list({pageSize:100000})).rows||[]),dateKeys:["request_date","created_at"]},
 {id:"certificates",title:"Certificate Log",description:"Issued certificates and dates.",tint:"t-blue",icon:ScrollText,fetch:async()=>((await window.mms.certificates.list({pageSize:100000})).rows||[]),columns:["certificate_number","type","issued_to","issued_date","issued_by"],dateKeys:["issued_date","created_at"]},
 {id:"audit",title:"Audit Log",description:"User actions across modules.",tint:"t-rose",icon:ShieldCheck,fetch:async()=>((await window.mms.audit.list({pageSize:100000})).rows||[]),columns:["created_at","username","action","module","description"],dateKeys:["created_at"]},
];

const esc=(v:any)=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;");
const escapeCsv=(v:any)=>{const s=String(v??"");return /[,\n\"]/.test(s)?`"${s.replace(/\"/g,'\"\"')}"`:s;};
const cols=(rows:any[],preferred?:string[])=>{const present=preferred?.filter(k=>Object.prototype.hasOwnProperty.call(rows[0]||{},k))||[];return present.length?present:Object.keys(rows[0]||{});};
const csv=(rows:any[],c:string[])=>[c.join(","),...rows.map(r=>c.map(k=>escapeCsv(r[k])).join(","))].join("\n");
const rowDate=(row:any,keys:string[])=>{for(const k of keys){if(row?.[k]){const d=new Date(row[k]);if(!Number.isNaN(d.getTime()))return d;}}return null;};

function crc32(data:Uint8Array){let c=0xffffffff;for(let i=0;i<data.length;i++){c^=data[i];for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}
function u16(n:number){return new Uint8Array([n&255,(n>>>8)&255]);}
function u32(n:number){return new Uint8Array([n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255]);}
function joinBytes(parts:Uint8Array[]){const out=new Uint8Array(parts.reduce((n,p)=>n+p.length,0));let o=0;for(const p of parts){out.set(p,o);o+=p.length;}return out;}
function xmlCell(ref:string,value:any,header=false){const s=esc(value);return typeof value==="number"&&Number.isFinite(value)?`<c r="${ref}" t="n"${header?' s="1"':''}><v>${value}</v></c>`:`<c r="${ref}" t="inlineStr"${header?' s="1"':''}><is><t>${s}</t></is></c>`;}
function excelCol(n:number){let s="";for(let x=n+1;x;x=Math.floor((x-1)/26))s=String.fromCharCode(65+(x-1)%26)+s;return s;}
function buildXlsx(rows:any[],c:string[]){
  const encoder=new TextEncoder();
  const sheetRows=[`<row r="1">${c.map((k,i)=>xmlCell(`${excelCol(i)}1`,k.replace(/_/g," "),true)).join("")}</row>`];
  rows.forEach((r,ri)=>{const rr=ri+2;sheetRows.push(`<row r="${rr}">${c.map((k,ci)=>xmlCell(`${excelCol(ci)}${rr}`,r[k])).join("")}</row>`);});
  const files:{name:string;data:Uint8Array}[]=[
    {name:"[Content_Types].xml",data:encoder.encode(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>`)},
    {name:"_rels/.rels",data:encoder.encode(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`)},
    {name:"xl/workbook.xml",data:encoder.encode(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Report" sheetId="1" r:id="rId1"/></sheets></workbook>`)},
    {name:"xl/_rels/workbook.xml.rels",data:encoder.encode(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`)},
    {name:"xl/styles.xml",data:encoder.encode(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Poppins"/></font><font><b/><sz val="11"/><name val="Poppins"/></font></fonts><fills count="1"><fill><patternFill patternType="none"/></fill></fills><borders count="1"><border/></borders><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/><xf numFmtId="0" fontId="1" fillId="0" borderId="0" applyFont="1"/></cellXfs></styleSheet>`)},
    {name:"xl/worksheets/sheet1.xml",data:encoder.encode(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"/></sheetViews><sheetData>${sheetRows.join("")}</sheetData></worksheet>`)}
  ];
  const locals:Uint8Array[]=[];const centrals:Uint8Array[]=[];let offset=0;
  for(const f of files){const name=encoder.encode(f.name),data=f.data,crc=crc32(data);const local=joinBytes([u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),name,data]);locals.push(local);centrals.push(joinBytes([u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name]));offset+=local.length;}
  const cd=joinBytes(centrals),all=joinBytes([...locals,[cd], [joinBytes([u32(0x06054b50),u16(0),u16(0),u16(files.length),u16(files.length),u32(cd.length),u32(offset),u16(0)])]]);
  return all;
}

export function Reports(){
 const {t,lang}=useI18n(); const ml=lang==="ml";
 const [range,setRange]=useState<"all"|"thisMonth"|"lastMonth"|"custom">("all"); const [from,setFrom]=useState(""); const [to,setTo]=useState(""); const [busy,setBusy]=useState<string|null>(null); const [busyFmt,setBusyFmt]=useState<string|null>(null);
 const bounds=()=>{const now=new Date();if(range==="all")return [null,null] as const;if(range==="custom")return [from?new Date(`${from}T00:00:00`):null,to?new Date(`${to}T23:59:59`):null] as const;const y=now.getFullYear(),m=now.getMonth();return range==="thisMonth"?[new Date(y,m,1),new Date(y,m+1,0,23,59,59)] as const:[new Date(y,m-1,1),new Date(y,m,0,23,59,59)] as const;};
 const filtered=(rows:any[],r:ReportType)=>{const [a,b]=bounds();if(!a&&!b)return rows;return rows.filter(x=>{const d=rowDate(x,r.dateKeys);return d?(!a||d>=a)&&(!b||d<=b):false;});};
 const triggerDownload=(bytes:Uint8Array,mime:string,name:string)=>{const url=URL.createObjectURL(new Blob([bytes],{type:mime}));const a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const exportReport=async(r:ReportType,f:"csv"|"excel"|"pdf")=>{setBusy(r.id);setBusyFmt(f);try{const raw=await r.fetch();const rows=filtered(raw,r);if(!rows.length){toast.warning(`${t("rpt_no_records")} "${r.title}"`);return;}const c=cols(rows,r.columns);const stamp=new Date().toISOString().slice(0,10);const name=`${r.id}_${range}_${stamp}`;if(f==="csv")triggerDownload(new TextEncoder().encode("\ufeff"+csv(rows,c)),"text/csv;charset=utf-8",`${name}.csv`);else if(f==="excel")triggerDownload(buildXlsx(rows,c),"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",`${name}.xlsx`);else{const html=`<!doctype html><html><head><meta charset="utf-8"><style>@page{size:A4 landscape;margin:10mm}body{font:12px Poppins,Arial,sans-serif;color:#1e2b25}h1{font-size:18px;margin:0 0 6px}p{margin:0 0 12px;color:#5f7268}table{width:100%;border-collapse:collapse}th,td{padding:5px;border:1px solid #dfe8e1;text-align:left;vertical-align:top}th{background:#f6f9f6}</style></head><body><h1>${esc(r.title)}</h1><p>Minz Mahallu Management System · ${rows.length} records · ${range}</p><table><tr>${c.map(k=>`<th>${esc(k.replace(/_/g," "))}</th>`).join("")}</tr>${rows.map(x=>`<tr>${c.map(k=>`<td>${esc(x[k])}</td>`).join("")}</tr>`).join("")}</table></body></html>`;const result=await window.mms.pdf.generate(html,`${name}.pdf`);if(result?.success===false&&!result?.cancelled)throw new Error(result.error||t("rpt_pdf_failed"));}toast.success(`${r.title}: ${rows.length} ${f.toUpperCase()}`);}catch(e:any){toast.error(e.message||t("ui_failed_save"));}finally{setBusy(null);setBusyFmt(null);}};
 const labels=ml?{all:"എല്ലാ തീയതികളും",thisMonth:"ഈ മാസം",lastMonth:"കഴിഞ്ഞ മാസം",custom:"ഇഷ്ടാനുസൃതം"}:{all:"All time",thisMonth:"This month",lastMonth:"Last month",custom:"Custom dates"};
 return <div className="view view-enter"><div className="vhead"><div className="modic t-em"><BarChart3 size={20}/></div><div><h1>{t("rpt_title")}</h1><div className="vs">{t("rpt_subtitle")}</div></div></div>
 <div className="card card-pad-4 mb-4"><div className="flex items-center gap-3 flex-wrap"><div className="flex items-center gap-2 report-range-title"><CalendarRange size={18}/><b>{ml?"റിപ്പോർട്ട് തീയതി":"Report date"}</b></div><div className="report-range-field"><Select value={range} onChange={e=>setRange(e.target.value as any)} className="w-44">{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</Select></div>{range==="custom"&&<><div className="report-range-field"><label className="lbl">{ml?"മുതൽ":"From"}</label><Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></div><div className="report-range-field"><label className="lbl">{ml?"വരെ":"To"}</label><Input type="date" value={to} onChange={e=>setTo(e.target.value)}/></div></>}</div></div>
 <div className="rep-sec"><b>{t("rpt_catalogue")}</b></div><div className="rep-grid">{REPORTS.map(r=>{const Icon=r.icon;const loading=busy===r.id;return <div key={r.id} className={`rep-card ${r.tint}`}><div className="ric"><Icon size={20}/></div><div className="rtitle">{r.title}</div><div className="rdesc">{r.description}</div><div className="rexps"><button className="btn bs bg" onClick={()=>exportReport(r,"csv")} disabled={loading}>{loading&&busyFmt==="csv"?<Loader2 size={12} className="animate-spin"/>:<Download size={12}/>}CSV</button><button className="btn bs bg" onClick={()=>exportReport(r,"excel")} disabled={loading}>{loading&&busyFmt==="excel"?<Loader2 size={12} className="animate-spin"/>:<FileSpreadsheet size={12}/>}Excel</button><button className="btn bs bp" onClick={()=>exportReport(r,"pdf")} disabled={loading}>{loading&&busyFmt==="pdf"?<Loader2 size={12} className="animate-spin"/>:<FileText size={12}/>}PDF</button></div></div>})}</div></div>;
}
